#define MRUBY_VERSION "v1.0.0"
#define MRUBY_PATCHLEVEL 0
#define MRUBY_REVISION 0

#define MRUBY_RELEASE_DATE "2014-01-10"
#define MRUBY_RELEASE_YEAR 2014
#define MRUBY_RELEASE_MONTH 1
#define MRUBY_RELEASE_DAY 10

