.TH "MIRB" 1 "2013-02-09" "MIRB" "MIRB"

.SH NAME
mirb \- Embeddable Interactive Ruby Shell

.SH SYNOPSIS
.B mirb

.SH DESCRIPTION
This manual page documents briefly the \fBmirb\fP.

This is a very early version, please test and report errors.
.PP

.SH AUTHOR
This manual page was written by Nobuhiro Iwamatsu <iwamatsu@debian.org>
for the Debian GNU/Linux system (but may be used by others).
