.TH "MIRB" 1 "2013-02-09" "MIRB" "MIRB"

.SH NAME
mirb \- Embeddable Interactive Ruby Shell

.SH SYNOPSIS
.B mirb
[ potions ]

.SH DESCRIPTION
This manual page documents briefly the \fBmirb\fP.

.PP
.SH OPTIONS
.B \-v
Print version number, then trun on verbose mode.
.TP
.B \-\-verbose
Run in verbose mode.
.TP
.B \-\-version
Print the version.
.TP
.B \-\-copyright
Print the copyright.

.SH AUTHOR
This manual page was written by Nobuhiro Iwamatsu <iwamatsu@debian.org>
for the Debian GNU/Linux system (but may be used by others).
