.TH "MRDB" "1" "2014-12-08" "MRDB" "MRDB"

.SH NAME
mrdb \- mruby debugger

.SH SYNOPSIS
.B mrdb
[ potions ] programfile

.SH DESCRIPTION
This manual page documents briefly the \fBmrdb\fP.

.PP
.SH OPTIONS
.TP
.B \-b
load and execute RiteBinary (mrb) file
.TP
.B \-d
specify source directory
.TP
.B \-\-version
Print the version.
.TP
.B \-\-copyright
Print the copyright.

.SH AUTHOR
This manual page was written by Akira Mitsui <murase.syuka@gmail.com>
for the Debian GNU/Linux system (but may be used by others).
