.TH "MRUBY-STRIP" 1 "2014-12-08" "MRUBY-STRIP" "MRUBY-STRIP"

.SH NAME
mruby-strip \- Discard symbols from object files.

.SH SYNOPSIS
.B mruby-strip
[ potions ] irepfiles

.SH DESCRIPTION
This manual page documents briefly the \fBmruby-strip\fP.

.PP
.SH OPTIONS
.TP
.B \-l, \-\-lvar   
remove LVAR section too.

.SH AUTHOR
This manual page was written by Akira Mitsui <murase.syuka@gmail.com>
for the Debian GNU/Linux system (but may be used by others).

