# Generate the table String#succ reads to tell a letter from a digit above
# ASCII, from the Unicode Character Database.
#
#   ruby mrbgems/mruby-string-ext/tools/gen_alnum.rb mrbgems/mruby-string-ext/src [UCDDIR]
#
# UCDDIR holds the database files as published under
# https://www.unicode.org/Public/<version>/ucd/, and defaults to the copy
# tools/unicode/ucd.rb names, the same one the other generators read. The files
# are not in the repository: they are read when the table is regenerated and
# nowhere else. Which characters are letters and which are digits is
# tools/unicode/ctype_data.rb's to say, the one place that reads the database
# for every table; this file only packs the answer for two of its types.
#
# String#succ steps the rightmost letter or digit of a string and wraps it at
# the end of its own run, so what it asks of a codepoint is which of the two it
# is, and where the run it belongs to starts. The two are the same properties
# [[:alpha:]] and [[:digit:]] hold, Alphabetic and the decimal digits, which is
# what CRuby's `enc_succ_alnum_char()` asks its encoding.
#
# str_alnum.h is compiled only into a build that reads its strings as
# characters and classifies them by Unicode. ASCII is not in the table: the
# letters and digits there are the ones ISALNUM() answers for, and every build
# steps those.
#
# A run is one 32-bit entry: the codepoint it starts at in the high 21 bits and
# which of the two it is in the low 2. Nothing is both, so cutting the
# codepoint space where that answer changes leaves each run a maximal stretch
# of one kind, which is the run succ wraps at.

require_relative '../../../tools/unicode/ctype_data'

outdir = ARGV[0] or abort "usage: #{$0} OUTDIR [UCDDIR]"
data = Unicode::CtypeData.load(ARGV[1])
version = data.version

MIN_CP = 0x80
MAX_CP = 0x10FFFF
MASK_BITS = 2
MAX_START = (1 << 21) - 1

# ------------------------------------------------------------------- gather

names = %w[alpha digit]

mask = Array.new(MAX_CP + 1, 0)
names.each_with_index do |name, bit|
  data.types.fetch(name).each do |lo, hi|
    ([lo, MIN_CP].max..hi).each { |cp| mask[cp] |= 1 << bit }
  end
end

overlap = (MIN_CP..MAX_CP).find { |cp| mask[cp] == 0b11 }
abort "U+%04X is both a letter and a digit" % overlap if overlap

runs = []   # [start, mask]
prev = nil
(MIN_CP..MAX_CP).each do |cp|
  next if mask[cp] == prev
  runs << [cp, mask[cp]]
  prev = mask[cp]
end

counts = names.map do |name|
  above = data.types.fetch(name).select { |_, hi| hi >= MIN_CP }
  cps = above.sum { |lo, hi| hi - [lo, MIN_CP].max + 1 }
  [name, above.size, cps]
end

# ------------------------------------------------------------------- emit

File.open(File.join(outdir, 'str_alnum.h'), 'w') do |out|
  out.puts <<~HEAD
    /*
    ** str_alnum.h - which codepoints above ASCII String#succ steps
    **
    ** Generated by mrbgems/mruby-string-ext/tools/gen_alnum.rb from the
    ** Unicode #{version} character database. Do not edit by hand.
    **
    ** The letters are the derived property Alphabetic and the digits the
    ** decimal digits, which is what CRuby's `enc_succ_alnum_char()` asks its
    ** encoding for. ASCII is not in the table: ISALNUM() answers for it.
    **
    ** See Copyright Notice in mruby.h
    */

    #ifndef MRB_STR_ALNUM_H
    #define MRB_STR_ALNUM_H

    /* Which of the two a run holds, or neither. */
    #define STR_ALNUM_ALPHA 0x1
    #define STR_ALNUM_DIGIT 0x2

    /* One run of codepoints of one kind, as a 32-bit entry:

         bits 0-#{MASK_BITS - 1}   which kind, or 0 for neither
         bits #{MASK_BITS}-31  the codepoint the run starts at

       Ascending; a run ends where the next begins, and the last at U+10FFFF.
       The first starts at U+0080, so a codepoint above ASCII is always inside
       one. Nothing is both a letter and a digit, so a run of either kind is as
       long as that kind goes: it is the run succ wraps at. */
    #define STR_ALNUM_MASK_BITS #{MASK_BITS}
    #define STR_ALNUM_MIN 0x#{'%04X' % MIN_CP}

    static const uint32_t str_alnum_runs[] = {
  HEAD
  runs.each do |start, m|
    abort "run at 0x%05X: start does not fit" % start if start > MAX_START
    out.puts "  0x%08X,  /* U+%04X %s */" % [(start << MASK_BITS) | m, start,
                                             m == 0 ? "-" : names[m - 1]]
  end
  out.puts <<~TAIL
    };

    #define STR_ALNUM_RUN_COUNT (sizeof(str_alnum_runs) / sizeof(str_alnum_runs[0]))

  TAIL
  alpha, digit = counts
  out.puts "/* #{runs.size} runs: #{alpha[2]} letters in #{alpha[1]} ranges and " \
           "#{digit[2]} digits in\n   #{digit[1]} ranges. */"
  out.puts
  out.puts "#endif /* MRB_STR_ALNUM_H */"
end

$stderr.puts "wrote #{File.join(outdir, 'str_alnum.h')}: #{runs.size} runs, #{runs.size * 4} bytes"
