require "mruby/source"

# The revision the source tree sits at reaches the build as a generated
# `mruby/revision.h`. `src/version.c` is alone in including it, so the revision
# reaches the `MRUBY_REVISION` constant while every other object is compiled
# without it: a commit recompiles one object rather than the whole tree, which
# is what a define holding the revision would cost.
#
# `#{build_dir}/include` is already on every compiler's include path, put there
# by `tasks/presym.rake` for the headers it generates.
#
# Whether the header is there at all is something only the build knows, so the
# build says it, with `MRB_REVISION_HEADER`. Asking the compiler instead, with
# `__has_include`, would have left the revision out of every build made by a
# compiler that has no such operator (MSVC before 2017, GCC before 5), the
# header sitting there unread.
#
# The define belongs to the flags an object is compiled with, and a rule
# resolved with flags other than the ones the compile after it uses discards
# the output it finds (`Command::Compiler#discard_foreign_output`). The walk in
# `tasks/presym.rake` resolves the rules for the preprocessed files as it is
# loaded, so `Rakefile` loads this file ahead of it.

# The header is written on every build, so that a commit made between two
# builds is not missed, but only where its content actually changed: an
# unchanged header keeps its timestamp, and the object that includes it is left
# alone.
revision_header_content = ->() do
  # No define at all where there is no revision to name: what a build with
  # nothing to read reports is `mruby/version.h`'s to say, and it says
  # `"HEAD"`.
  #
  # Guarded, so that a build config naming a revision of its own says it: a
  # `-D` on the command line is defined before this header is read, and an
  # unguarded define here would be a redefinition of it.
  body = if MRuby::Source::MRUBY_FULL_REVISION.empty?
           "/* The build found no repository to read a revision from. */\n"
         else
           {"MRUBY_REVISION" => MRuby::Source::MRUBY_REVISION,
            "MRUBY_FULL_REVISION" => MRuby::Source::MRUBY_FULL_REVISION}.map do |name, revision|
             "#ifndef #{name}\n#define #{name} #{revision.inspect}\n#endif\n"
           end.join
         end
  <<~HEADER
    /*
    ** mruby/revision.h - the source revision this build was made from
    **
    ** Generated by `tasks/revision.rake`. Do not edit.
    */

    #ifndef MRUBY_REVISION_H
    #define MRUBY_REVISION_H

    #{body}
    #endif  /* MRUBY_REVISION_H */
  HEADER
end

MRuby.each_target do |build|
  # `src/version.c` is compiled into libmruby, and a build without one has
  # nothing to tell the revision to.
  next unless build.libmruby_enabled?

  # Internal, so that the amalgam leaves it out of the defines it bakes into
  # its header (`MRuby::Amalgam#collect_build_defines`): the consumer of an
  # amalgam has no generated header to include, and carries the revision in
  # the amalgam's own header instead.
  build.compilers.each{|c| c.internal_defines << "MRB_REVISION_HEADER"}

  header = "#{build.build_dir}/include/mruby/revision.h"

  revision_task = file header do |t|
    content = revision_header_content.()
    next if File.exist?(t.name) && File.binread(t.name) == content
    mkdir_p File.dirname(t.name)
    File.binwrite(t.name, content)
    _pp "GEN", t.name.relative_path
  end

  # A file task with no prerequisites is done as soon as the file exists, and
  # the revision changes with no file of the build's changing. Ask for the task
  # every time, and let it decide whether the header it writes differs from the
  # one on disk.
  revision_task.define_singleton_method(:needed?) { true }

  # The source is named here as well, and first: the rule that compiles the
  # object takes its first prerequisite as the input, and the rule is resolved
  # after this file is loaded, so the header alone would be handed to the
  # compiler in the source's place.
  file build.objfile("#{build.build_dir}/src/version") =>
    ["#{MRUBY_ROOT}/src/version.c", header]
end
