/*
** re_cased.h - codepoints /i cannot answer without Unicode case data
**
** Generated by mrbgems/mruby-regexp/tools/gen_cased.rb from the Unicode
** 17.0.0 character database. Do not edit by hand.
**
** A build without MRB_UNICODE_CASE refuses to compile an /i pattern
** holding one of these, rather than folding ASCII and answering wrongly.
** The test is whether a codepoint has a case folding, not whether it is
** non-ASCII: a script without case has nothing to fold, so /日本/i and the
** like are unaffected and stay out of the table.
**
** U+017F and U+212A are out of the table as well, for the opposite reason:
** they fold to "s" and "k", so every build carries them and can answer.
**
** Ranges are coarse. 309 uncased codepoints fall inside them and are
** refused too, which costs a pattern ASCII folding would have got right
** and buys a table a tenth the size of the mapping.
**
** See Copyright Notice in mruby.h
*/

#ifndef MRB_RE_CASED_H
#define MRB_RE_CASED_H

/* Inclusive (lo, hi) pairs, ascending and disjoint. */
static const uint32_t re_cased_ranges[][2] = {
  { 0x000B5, 0x0017E },
  { 0x00180, 0x0029E },
  { 0x00345, 0x00345 },
  { 0x00370, 0x00587 },
  { 0x010A0, 0x010FF },
  { 0x013A0, 0x013FD },
  { 0x01C80, 0x01CBF },
  { 0x01D79, 0x01D8E },
  { 0x01E00, 0x01FFC },
  { 0x02126, 0x02129 },
  { 0x0212B, 0x02132 },
  { 0x0214E, 0x0214E },
  { 0x02160, 0x02184 },
  { 0x024B6, 0x024E9 },
  { 0x02C00, 0x02D2D },
  { 0x0A640, 0x0A66D },
  { 0x0A680, 0x0A69B },
  { 0x0A722, 0x0A7DC },
  { 0x0A7F5, 0x0A7F6 },
  { 0x0AB53, 0x0AB53 },
  { 0x0AB70, 0x0ABBF },
  { 0x0FB00, 0x0FB17 },
  { 0x0FF21, 0x0FF5A },
  { 0x10400, 0x1044F },
  { 0x104B0, 0x104FB },
  { 0x10570, 0x105BC },
  { 0x10C80, 0x10CF2 },
  { 0x10D50, 0x10D85 },
  { 0x118A0, 0x118DF },
  { 0x16E40, 0x16E7F },
  { 0x16EA0, 0x16ED3 },
  { 0x1E900, 0x1E943 },
};

#define RE_CASED_RANGE_COUNT (sizeof(re_cased_ranges) / sizeof(re_cased_ranges[0]))

/* Lowest and highest codepoint covered, so a lookup that cannot hit
   anything costs one comparison. */
#define RE_CASED_MIN 0x000B5
#define RE_CASED_MAX 0x1E943

/* 2982 cased codepoints in 32 ranges spanning 3291. */

#endif /* MRB_RE_CASED_H */
