# Generate re_casefold.h from the Unicode simple case folding data that the
# host CRuby carries. Phase 1 covers 1:1 foldings only; a codepoint whose fold
# is more than one codepoint (U+00DF -> "ss") is skipped and listed at the end
# of the header as a comment.
#
#   ruby mrbgems/mruby-regexp/tools/gen_casefold.rb > mrbgems/mruby-regexp/src/re_casefold.h

pairs = []
skipped = []
(0x80..0x10FFFF).each do |cp|
  next if cp.between?(0xD800, 0xDFFF)
  c = begin; cp.chr("UTF-8"); rescue RangeError; next; end
  f = c.downcase(:fold)
  next if f == c
  if f.length == 1
    pairs << [cp, f.ord]
  else
    skipped << [cp, f]
  end
end

# Run-length encode: consecutive sources stepping by a fixed stride and sharing
# one delta collapse into a single entry. Stride is 1 or 2 in practice, the
# latter being the interleaved upper/lower blocks (Latin Extended, Cyrillic).
runs = []
pairs.each do |cp, to|
  d = to - cp
  r = runs.last
  if r && r[:delta] == d
    stride = cp - r[:last]
    if stride <= 2 && (r[:stride].nil? || r[:stride] == stride)
      r[:stride] ||= stride
      r[:count] += 1
      r[:last] = cp
      next
    end
  end
  runs << {start: cp, last: cp, count: 1, stride: nil, delta: d}
end
runs.each { |r| r[:stride] ||= 1 }

puts <<~HEAD
  /*
  ** re_casefold.h - Unicode simple case folding table (1:1 foldings)
  **
  ** Generated by tools/gen_casefold.rb from Unicode #{RbConfig::CONFIG['UNICODE_VERSION'] || 'data'}
  ** as carried by ruby #{RUBY_VERSION}. Do not edit by hand.
  **
  ** Sources below 128 are not in the table: ASCII folding is done inline by
  ** the compiler. A source whose fold is more than one codepoint is not in
  ** the table either; those are listed at the end of this file.
  **
  ** See Copyright Notice in mruby.h
  */

  /* One run of sources start, start+stride, ... (count entries), each folding
     to the source plus delta. */
  typedef struct re_fold_run {
    uint32_t start;
    uint16_t count;
    uint8_t stride;
    int32_t delta;
  } re_fold_run;

  static const re_fold_run re_fold_runs[] = {
HEAD

runs.each do |r|
  puts "  { 0x%05X, %4d, %d, %7d }," % [r[:start], r[:count], r[:stride], r[:delta]]
end

puts <<~TAIL
  };

  #define RE_FOLD_RUN_COUNT (sizeof(re_fold_runs) / sizeof(re_fold_runs[0]))

  /* Lowest and highest source codepoint in the table, so a lookup that cannot
     hit anything costs one comparison. */
  #define RE_FOLD_MIN 0x#{'%05X' % runs.map { |r| r[:start] }.min}
  #define RE_FOLD_MAX 0x#{'%05X' % runs.map { |r| r[:start] + (r[:count] - 1) * r[:stride] }.max}
TAIL

puts
puts "/* #{pairs.size} source codepoints in #{runs.size} runs. */"
puts "/*"
puts " * Not covered (fold is more than one codepoint), #{skipped.size} sources:"
skipped.each_slice(6) do |slice|
  puts " *   " + slice.map { |cp, f| "U+%04X" % cp }.join(" ")
end
puts " */"
