# Generate the two case folding headers from the Unicode simple case folding
# data that the host CRuby carries.
#
#   ruby mrbgems/mruby-regexp/tools/gen_casefold.rb mrbgems/mruby-regexp/src
#
# re_casefold.h holds the mapping, and is compiled only into a build that
# defines MRB_REGEXP_UNICODE_CASE. It holds the foldings that pair one
# codepoint with one other; a codepoint with no such counterpart (U+FB00 to
# "ff") is skipped and listed at the end of the header as a comment.
#
# re_cased.h holds the ranges a build without that option must refuse under
# /i, and is compiled only into such a build. Both come from one pass over the
# same data so that the second cannot drift into letting through a codepoint
# the first would have folded.

require 'rbconfig'
require 'set'

outdir = ARGV[0] or abort "usage: #{$0} OUTDIR"

pairs = []      # [source, counterpart] for the foldings that pair one with one
skipped = []    # [source, fold] where no single counterpart exists
cased = Set.new # every codepoint that either folds or is folded to

(0x80..0x10FFFF).each do |cp|
  next if cp.between?(0xD800, 0xDFFF)
  c = begin; cp.chr("UTF-8"); rescue RangeError; next; end
  f = c.downcase(:fold)
  next if f == c
  cased << cp
  to = nil
  if f.length == 1
    to = f.ord
  else
    # A fold of several codepoints can still leave a single counterpart the
    # engine can use: U+1E9E lower cases to U+00DF, and the two fold alike, so
    # /ß/i reaching "ẞ" needs no more than the 1:1 machinery. Only a source
    # with no such counterpart at all (U+FB00 to "ff") is out of reach.
    lo = c.downcase
    to = lo.ord if lo.length == 1 && lo != c && lo.downcase(:fold) == f
  end
  if to
    pairs << [cp, to]
    cased << to
  else
    skipped << [cp, f]
  end
end

# A folding whose target is ASCII is carried by every build, not just the one
# that asks for the option: U+017F folds to "s" and U+212A to "k", and those
# two are what makes "ASCII case folding" mean the whole equivalence class
# rather than the part of it that happens to be ASCII. They are therefore not
# among the codepoints an ASCII-only build has to refuse.
ascii_reachable = pairs.select { |_, to| to < 0x80 }.map(&:first).to_set

# ---------------------------------------------------------------- re_casefold.h

# Run-length encode: consecutive sources stepping by a fixed stride and sharing
# one delta collapse into a single entry. Stride is 1 or 2 in practice, the
# latter being the interleaved upper/lower blocks (Latin Extended, Cyrillic).
runs = []
pairs.each do |cp, to|
  d = to - cp
  r = runs.last
  if r && r[:delta] == d
    stride = cp - r[:last]
    if stride <= 2 && (r[:stride].nil? || r[:stride] == stride)
      r[:stride] ||= stride
      r[:count] += 1
      r[:last] = cp
      next
    end
  end
  runs << {start: cp, last: cp, count: 1, stride: nil, delta: d}
end
runs.each { |r| r[:stride] ||= 1 }

File.open(File.join(outdir, 're_casefold.h'), 'w') do |out|
  out.puts <<~HEAD
    /*
    ** re_casefold.h - Unicode simple case folding table (1:1 foldings)
    **
    ** Generated by tools/gen_casefold.rb from Unicode #{RbConfig::CONFIG['UNICODE_VERSION'] || 'data'}
    ** as carried by ruby #{RUBY_VERSION}. Do not edit by hand.
    **
    ** Sources below 128 are not in the table: ASCII folding is done inline by
    ** the compiler. A source with no single counterpart to pair with is not in
    ** the table either; those are listed at the end of this file.
    **
    ** See Copyright Notice in mruby.h
    */

    /* One run of sources start, start+stride, ... (count entries), each folding
       to the source plus delta. */
    typedef struct re_fold_run {
      uint32_t start;
      uint16_t count;
      uint8_t stride;
      int32_t delta;
    } re_fold_run;

    static const re_fold_run re_fold_runs[] = {
  HEAD

  runs.each do |r|
    out.puts "  { 0x%05X, %4d, %d, %7d }," % [r[:start], r[:count], r[:stride], r[:delta]]
  end

  out.puts <<~TAIL
    };

    #define RE_FOLD_RUN_COUNT (sizeof(re_fold_runs) / sizeof(re_fold_runs[0]))

    /* Lowest and highest source codepoint in the table, so a lookup that cannot
       hit anything costs one comparison. */
    #define RE_FOLD_MIN 0x#{'%05X' % runs.map { |r| r[:start] }.min}
    #define RE_FOLD_MAX 0x#{'%05X' % runs.map { |r| r[:start] + (r[:count] - 1) * r[:stride] }.max}
  TAIL

  out.puts
  out.puts "/* #{pairs.size} source codepoints in #{runs.size} runs. */"
  out.puts "/*"
  out.puts " * Not covered (no single codepoint counterpart), #{skipped.size} sources:"
  skipped.each_slice(6) do |slice|
    out.puts " *   " + slice.map { |cp, _| "U+%04X" % cp }.join(" ")
  end
  out.puts " */"
end

# ------------------------------------------------------------------ re_cased.h

# Coarse ranges over the cased codepoints an ASCII-only build cannot fold.
# Neighbours closer together than GAP are merged, which trades a handful of
# uncased codepoints inside the ranges, refused under /i even though ASCII
# folding would have answered them correctly, for a table an order of
# magnitude smaller than the mapping it stands in for.
GAP = 16

refuse = (cased - ascii_reachable).select { |cp| cp >= 0x80 }.sort
ranges = []
refuse.each do |cp|
  r = ranges.last
  if r && cp - r[1] <= GAP + 1
    r[1] = cp
  else
    ranges << [cp, cp]
  end
end

# Merging closes over the two ASCII reachable sources again, since each sits
# one codepoint away from a cased neighbour. Punch them back out, so that the
# table means what it says and the lookup needs no exception beside it.
ascii_reachable.sort.each do |cp|
  ranges = ranges.flat_map do |lo, hi|
    next [[lo, hi]] unless cp.between?(lo, hi)
    [(lo <= cp - 1 ? [lo, cp - 1] : nil), (cp + 1 <= hi ? [cp + 1, hi] : nil)].compact
  end
end

covered = ranges.sum { |lo, hi| hi - lo + 1 }

File.open(File.join(outdir, 're_cased.h'), 'w') do |out|
  out.puts <<~HEAD
    /*
    ** re_cased.h - codepoints /i cannot answer without Unicode case data
    **
    ** Generated by tools/gen_casefold.rb from Unicode #{RbConfig::CONFIG['UNICODE_VERSION'] || 'data'}
    ** as carried by ruby #{RUBY_VERSION}. Do not edit by hand.
    **
    ** A build without MRB_REGEXP_UNICODE_CASE refuses to compile an /i pattern
    ** holding one of these, rather than folding ASCII and answering wrongly.
    ** The test is whether a codepoint has a case folding, not whether it is
    ** non-ASCII: a script without case has nothing to fold, so /#{'日本'}/i and the
    ** like are unaffected and stay out of the table.
    **
    ** U+017F and U+212A are out of the table as well, for the opposite reason:
    ** they fold to "s" and "k", so every build carries them and can answer.
    **
    ** Ranges are coarse. #{covered - refuse.size} uncased codepoints fall inside them and are
    ** refused too, which costs a pattern ASCII folding would have got right
    ** and buys a table a tenth the size of the mapping.
    **
    ** See Copyright Notice in mruby.h
    */

    /* Inclusive (lo, hi) pairs, ascending and disjoint. */
    static const uint32_t re_cased_ranges[][2] = {
  HEAD

  ranges.each do |lo, hi|
    out.puts "  { 0x%05X, 0x%05X }," % [lo, hi]
  end

  out.puts <<~TAIL
    };

    #define RE_CASED_RANGE_COUNT (sizeof(re_cased_ranges) / sizeof(re_cased_ranges[0]))

    /* Lowest and highest codepoint covered, so a lookup that cannot hit
       anything costs one comparison. */
    #define RE_CASED_MIN 0x#{'%05X' % ranges.first[0]}
    #define RE_CASED_MAX 0x#{'%05X' % ranges.last[1]}
  TAIL

  out.puts
  out.puts "/* #{refuse.size} cased codepoints in #{ranges.size} ranges spanning #{covered}. */"
end
