# Generate the character type table the POSIX brackets read above ASCII, from
# the Unicode Character Database.
#
#   ruby mrbgems/mruby-regexp/tools/gen_ctype.rb mrbgems/mruby-regexp/src [UCDDIR]
#
# UCDDIR holds UnicodeData.txt, DerivedCoreProperties.txt and PropList.txt as
# published under https://www.unicode.org/Public/<version>/ucd/, and defaults
# to the copy tools/unicode/ucd.rb names, the same one the case table
# generators read. The files are not in the repository: they are read when the
# table is regenerated and nowhere else. Which characters each type holds is
# tools/unicode/ctype_data.rb's to say; this file only packs the answer.
#
# re_ctype.h holds, for every codepoint above ASCII, which of the types a
# POSIX bracket can name it belongs to, and is compiled only into a build that
# reads its strings as characters and classifies them by Unicode. ASCII is not
# in the table: the compiler sets those bits from a list of its own, which
# every build carries.
#
# The types are held together rather than one table each. Every codepoint has
# one set of answers, so the codepoint space is cut into runs over which the
# set does not change, and a run is one 32-bit entry: the codepoint it starts
# at in the high 21 bits and the set in the low 11. One binary search answers
# all the types at once, and the runs number a fifth of what the types would
# take as separate range lists.
#
# `cntrl` is not in the set. Above ASCII it is the C1 controls and nothing
# else, one range that a lookup answers from two numbers, and leaving it out is
# what lets the set fit beside a codepoint in 32 bits.

require_relative '../../../tools/unicode/ctype_data'

outdir = ARGV[0] or abort "usage: #{$0} OUTDIR [UCDDIR]"
data = Unicode::CtypeData.load(ARGV[1])
version = data.version

MIN_CP = 0x80
MAX_CP = 0x10FFFF
MASK_BITS = 11
MAX_START = (1 << 21) - 1

# ------------------------------------------------------------------- gather

# The types with a bit in the table, in bit order, and the one answered from a
# range. The order is what re_internal.h names the bits in; the header spells
# each so that a build in which the two disagree fails to compile.
names = data.types.keys
cntrl = names.delete('cntrl')
abort "expected cntrl among the types" unless cntrl
abort "#{names.size} types do not fit #{MASK_BITS} bits" if names.size > MASK_BITS
cntrl_lo, cntrl_hi = data.cntrl_range

# The mask of every codepoint above ASCII, then the runs it is constant over.
mask = Array.new(MAX_CP + 1, 0)
names.each_with_index do |name, bit|
  data.types[name].each do |lo, hi|
    ([lo, MIN_CP].max..hi).each { |cp| mask[cp] |= 1 << bit }
  end
end

runs = []   # [start, mask]
prev = nil
(MIN_CP..MAX_CP).each do |cp|
  next if mask[cp] == prev
  runs << [cp, mask[cp]]
  prev = mask[cp]
end

# What each type comes to above ASCII, for the header to say.
counts = names.map do |name|
  above = data.types[name].select { |_, hi| hi >= MIN_CP }
  cps = above.sum { |lo, hi| hi - [lo, MIN_CP].max + 1 }
  [name, above.size, cps]
end

# ------------------------------------------------------------------- emit

File.open(File.join(outdir, 're_ctype.h'), 'w') do |out|
  out.puts <<~HEAD
    /*
    ** re_ctype.h - which character types a codepoint above ASCII belongs to
    **
    ** Generated by mrbgems/mruby-regexp/tools/gen_ctype.rb from the Unicode
    ** #{version} character database. Do not edit by hand.
    **
    ** What [[:alpha:]] and the other POSIX brackets hold above ASCII. ASCII is
    ** not in the table: the compiler sets those bits from a list of its own.
    ** The types are as CRuby's regexp engine reads them: alpha, upper and
    ** lower are the derived properties Alphabetic, Uppercase and Lowercase,
    ** digit the decimal digits, word the letters, marks, decimal digits,
    ** connector punctuation and the two joiners U+200C and U+200D, punct the
    ** punctuation categories, space the White_Space property, blank the space
    ** separators, graph everything but the spaces, controls, surrogates and
    ** unassigned, and print that plus the space separators.
    **
    ** See Copyright Notice in mruby.h
    */

    #ifndef MRB_RE_CTYPE_H
    #define MRB_RE_CTYPE_H

    /* The bit each type has in an entry, in the order re_internal.h assigns
       them; re_utf8.c checks that the two agree. */
  HEAD
  names.each_with_index do |name, bit|
    out.puts "#define RE_CTYPE_TABLE_#{name.upcase} 0x%03X" % (1 << bit)
  end
  out.puts <<~MID

    /* One run of codepoints sharing a set of types, as a 32-bit entry:

         bits  0-#{MASK_BITS - 1}  the set, one bit per type as above
         bits #{MASK_BITS}-31  the codepoint the run starts at

       Ascending; a run ends where the next begins, and the last at U+10FFFF.
       The first starts at U+0080, so a codepoint above ASCII is always inside
       one. */
    #define RE_CTYPE_MASK_BITS #{MASK_BITS}
    #define RE_CTYPE_MIN 0x#{'%04X' % MIN_CP}

    /* The C1 controls, which is what [[:cntrl:]] holds above ASCII. Not in the
       set: a lookup answers it from these two numbers instead. */
    #define RE_CTYPE_CNTRL_LO 0x#{'%04X' % cntrl_lo}
    #define RE_CTYPE_CNTRL_HI 0x#{'%04X' % cntrl_hi}

    static const uint32_t re_ctype_runs[] = {
  MID
  runs.each do |start, m|
    abort "run at 0x%05X: start does not fit" % start if start > MAX_START
    out.puts "  0x%08X,  /* U+%04X %s */" % [(start << MASK_BITS) | m, start,
                                             m == 0 ? "-" : names.each_index.select { |i| m[i] == 1 }.map { |i| names[i] }.join(" ")]
  end
  out.puts <<~TAIL
    };

    #define RE_CTYPE_RUN_COUNT (sizeof(re_ctype_runs) / sizeof(re_ctype_runs[0]))

  TAIL
  out.puts "/* #{runs.size} runs. Above ASCII each type holds:"
  counts.each do |name, nranges, cps|
    out.puts "     %-6s %7d codepoints in %4d ranges" % [name, cps, nranges]
  end
  out.puts "   and cntrl the #{cntrl_hi - cntrl_lo + 1} of U+#{'%04X' % cntrl_lo} to U+#{'%04X' % cntrl_hi}. */"
  out.puts
  out.puts "#endif /* MRB_RE_CTYPE_H */"
end

$stderr.puts "wrote #{File.join(outdir, 're_ctype.h')}: #{runs.size} runs, #{runs.size * 4} bytes"
