# Generate the table \p{...} reads for the general categories and the emoji
# properties, from the Unicode Character Database.
#
#   ruby mrbgems/mruby-regexp/tools/gen_prop.rb mrbgems/mruby-regexp/src [UCDDIR]
#
# UCDDIR holds UnicodeData.txt and emoji-data.txt as published under
# https://www.unicode.org/Public/<version>/ucd/ (the second in its emoji/
# directory), and defaults to the copy tools/unicode/ucd.rb names, the same
# one the other table generators read. The files are not in the repository.
#
# re_prop.h is read by the compiler alone: a property is spelled out as the
# ranges of a class when the pattern is compiled, so nothing here is asked at
# match time. It is compiled only into a build that classifies characters by
# Unicode, the same builds re_ctype.h is compiled into.
#
# The POSIX names (\p{Alpha}, \p{Word} and the rest) are not here. They are
# the types re_ctype.h carries, and the compiler reads them as the brackets
# they are the other spelling of.
#
# Two tables, since the properties come in two shapes. The general category
# is a partition, every codepoint having exactly one, so the codepoint space
# is cut into runs of one category and a run is one 32-bit entry: the
# codepoint it starts at in the high 21 bits and the category in the low 5.
# The emoji properties overlap each other, so their runs carry a set of them
# instead, the way re_ctype.h carries the POSIX types.

require_relative '../../../tools/unicode/ucd'

outdir = ARGV[0] or abort "usage: #{$0} OUTDIR [UCDDIR]"
dir = ARGV[1] || Unicode::UCD.dir
Unicode::UCD.verify(dir)
version = Unicode::UCD::VERSION

MAX_CP = 0x10FFFF
MAX_START = (1 << 21) - 1

# The categories in the order the table numbers them, the long-standing order
# of the Unicode Standard's table of them. Cn is last: a codepoint
# UnicodeData.txt does not list is unassigned.
CATEGORIES = %w[Lu Ll Lt Lm Lo Mn Mc Me Nd Nl No Pc Pd Ps Pe Pi Pf Po
        Sm Sc Sk So Zs Zl Zp Cc Cf Co Cs Cn]
GC_BITS = 5
abort "#{CATEGORIES.size} categories do not fit #{GC_BITS} bits" if CATEGORIES.size > (1 << GC_BITS)

EMOJI = %w[Emoji Emoji_Presentation Extended_Pictographic]
EMOJI_BITS = 3

# ------------------------------------------------------------------- gather

cn = CATEGORIES.index('Cn')
cat = Array.new(MAX_CP + 1, cn)
Unicode::UCD.general_categories(dir).each do |cp, gc|
  cat[cp] = CATEGORIES.index(gc) or abort "unknown general category #{gc} at U+%04X" % cp
end

emoji = Array.new(MAX_CP + 1, 0)
props = Unicode::UCD.property_ranges(dir, 'emoji-data.txt')
EMOJI.each_with_index do |name, bit|
  ranges = props[name]
  abort "emoji-data.txt lists no #{name}" if ranges.empty?
  ranges.each { |r| r.each { |cp| emoji[cp] |= 1 << bit } }
end

def runs_of(values)
  runs = []
  prev = nil
  values.each_with_index do |v, cp|
    next if v == prev
    runs << [cp, v]
    prev = v
  end
  runs
end

gc_runs = runs_of(cat)
emoji_runs = runs_of(emoji)
[gc_runs, emoji_runs].each do |runs|
  runs.each { |start, _| abort "run at 0x%05X: start does not fit" % start if start > MAX_START }
end

gc_counts = CATEGORIES.each_index.map { |i| cat.count(i) }
emoji_counts = EMOJI.each_index.map { |bit| emoji.count { |m| m[bit] == 1 } }

# ------------------------------------------------------------------- emit

path = File.join(outdir, 're_prop.h')
File.open(path, 'w') do |out|
  out.puts <<~HEAD
    /*
    ** re_prop.h - the general category and the emoji properties of a codepoint
    **
    ** Generated by mrbgems/mruby-regexp/tools/gen_prop.rb from the Unicode
    ** #{version} character database. Do not edit by hand.
    **
    ** What \\p{Lu}, \\p{L}, \\p{Emoji} and the rest hold. The compiler reads
    ** these when it builds a class and spells the property out as ranges, so
    ** nothing here is read at match time. The POSIX names are re_ctype.h's.
    **
    ** See Copyright Notice in mruby.h
    */

    #ifndef MRB_RE_PROP_H
    #define MRB_RE_PROP_H

    /* The general categories in the order the table numbers them. */
    static const char re_prop_gc_names[][3] = {
  HEAD
  CATEGORIES.each_slice(10) { |s| out.puts "  " + s.map { |n| "\"#{n}\"," }.join(" ") }
  out.puts <<~MID
    };
    #define RE_PROP_GC_COUNT #{CATEGORIES.size}

    /* One run of codepoints of one category, as a 32-bit entry: the category
       in bits 0-#{GC_BITS - 1} and the codepoint the run starts at in the bits
       above. Ascending from U+0000; a run ends where the next begins, and the
       last at U+10FFFF. */
    #define RE_PROP_GC_BITS #{GC_BITS}

    static const uint32_t re_prop_gc_runs[] = {
  MID
  gc_runs.each do |start, v|
    out.puts "  0x%08X,  /* U+%04X %s */" % [(start << GC_BITS) | v, start, CATEGORIES[v]]
  end
  out.puts <<~MID
    };
    #define RE_PROP_GC_RUN_COUNT (sizeof(re_prop_gc_runs) / sizeof(re_prop_gc_runs[0]))

    /* The emoji properties, one bit each in this order. */
    static const char *const re_prop_emoji_names[] = {
  MID
  EMOJI.each { |n| out.puts "  \"#{n}\"," }
  out.puts <<~MID
    };
    #define RE_PROP_EMOJI_COUNT #{EMOJI.size}

    /* One run of codepoints sharing a set of emoji properties: the set in bits
       0-#{EMOJI_BITS - 1} and the codepoint the run starts at above, as for the
       categories. */
    #define RE_PROP_EMOJI_BITS #{EMOJI_BITS}

    static const uint32_t re_prop_emoji_runs[] = {
  MID
  emoji_runs.each do |start, m|
    names = m == 0 ? '-' : EMOJI.each_index.select { |i| m[i] == 1 }.map { |i| EMOJI[i] }.join(' ')
    out.puts "  0x%08X,  /* U+%04X %s */" % [(start << EMOJI_BITS) | m, start, names]
  end
  out.puts <<~TAIL
    };
    #define RE_PROP_EMOJI_RUN_COUNT (sizeof(re_prop_emoji_runs) / sizeof(re_prop_emoji_runs[0]))

  TAIL
  out.puts "/* #{gc_runs.size} category runs and #{emoji_runs.size} emoji runs. Each holds:"
  CATEGORIES.each_with_index { |n, i| out.puts "     %-21s %7d codepoints" % [n, gc_counts[i]] }
  EMOJI.each_with_index { |n, i| out.puts "     %-21s %7d codepoints" % [n, emoji_counts[i]] }
  out.puts "*/"
  out.puts
  out.puts "#endif /* MRB_RE_PROP_H */"
end

total = (gc_runs.size + emoji_runs.size) * 4
$stderr.puts "wrote #{path}: #{gc_runs.size} + #{emoji_runs.size} runs, #{total} bytes"
