# Generate the codepoints /i cannot answer for, from the Unicode simple case
# folding data.
#
#   ruby mrbgems/mruby-regexp/tools/gen_cased.rb mrbgems/mruby-regexp/src [UCDDIR]
#
# UCDDIR holds UnicodeData.txt, SpecialCasing.txt and CaseFolding.txt as
# published under https://www.unicode.org/Public/<version>/ucd/, and defaults
# to the copy tools/unicode/case_data.rb names, the same one core's
# tools/gen_unicase.rb reads. The files are not in the repository: they are
# read when the table is regenerated and nowhere else.
#
# re_cased.h holds the ranges a build without the foldings must refuse under
# /i, and is compiled only into such a build. A build with them reads them off
# core's unicase.h and refuses nothing.
#
# The pass below reads the whole of the folding data even though only the
# refusals are written out, since what has to be refused is defined by what
# the other build folds: a codepoint is here exactly when it is missing there.

require 'set'
require_relative '../../../tools/unicode/case_data'

outdir = ARGV[0] or abort "usage: #{$0} OUTDIR [UCDDIR]"
data = Unicode::CaseData.load(ARGV[1])
version = data.version

# The lower case mapping, which is the full one where the character has one:
# the counterpart hunted below is the one a lower case away, and a character
# whose lower case is several characters has none. Folding is the full one,
# which is the folding core carries and therefore the one whose reach is at
# stake here.
lower = data.lower
fold = data.fold

pairs = []      # [source, counterpart] for the foldings that pair one with one
skipped = []    # [source, fold] where no single counterpart exists
cased = Set.new # every codepoint that either folds or is folded to

fold.keys.sort.each do |cp|
  next if cp < 0x80
  f = fold[cp]
  cased << cp
  to = nil
  if f.size == 1
    to = f[0]
  else
    # A fold of several codepoints can still leave a single counterpart the
    # engine can use: U+1E9E lower cases to U+00DF, and the two fold alike, so
    # /ß/i reaching "ẞ" needs no more than the 1:1 machinery. Only a source
    # with no such counterpart at all (U+FB00 to "ff") is out of reach.
    lo = lower[cp]
    to = lo[0] if lo && lo.size == 1 && lo != [cp] && (fold[lo[0]] || lo) == f
  end
  if to
    pairs << [cp, to]
    cased << to
  else
    skipped << [cp, f]
  end
end

# A folding whose target is ASCII is carried by every build, not just the one
# that reads characters: U+017F folds to "s" and U+212A to "k", and those
# two are what makes "ASCII case folding" mean the whole equivalence class
# rather than the part of it that happens to be ASCII. They are therefore not
# among the codepoints an ASCII-only build has to refuse.
ascii_reachable = pairs.select { |_, to| to < 0x80 }.map(&:first).to_set

# ------------------------------------------------------------------ re_cased.h

# Coarse ranges over the cased codepoints an ASCII-only build cannot fold.
# Neighbours closer together than GAP are merged, which trades a handful of
# uncased codepoints inside the ranges, refused under /i even though ASCII
# folding would have answered them correctly, for a table an order of
# magnitude smaller than the mapping it stands in for.
GAP = 16

refuse = (cased - ascii_reachable).select { |cp| cp >= 0x80 }.sort
ranges = []
refuse.each do |cp|
  r = ranges.last
  if r && cp - r[1] <= GAP + 1
    r[1] = cp
  else
    ranges << [cp, cp]
  end
end

# Merging closes over the two ASCII reachable sources again, since each sits
# one codepoint away from a cased neighbour. Punch them back out, so that the
# table means what it says and the lookup needs no exception beside it.
ascii_reachable.sort.each do |cp|
  ranges = ranges.flat_map do |lo, hi|
    next [[lo, hi]] unless cp.between?(lo, hi)
    [(lo <= cp - 1 ? [lo, cp - 1] : nil), (cp + 1 <= hi ? [cp + 1, hi] : nil)].compact
  end
end

covered = ranges.sum { |lo, hi| hi - lo + 1 }

File.open(File.join(outdir, 're_cased.h'), 'w') do |out|
  out.puts <<~HEAD
    /*
    ** re_cased.h - codepoints /i cannot answer without Unicode case data
    **
    ** Generated by mrbgems/mruby-regexp/tools/gen_cased.rb from the Unicode
    ** #{version} character database. Do not edit by hand.
    **
    ** A build without MRB_UNICODE_CASE refuses to compile an /i pattern
    ** holding one of these, rather than folding ASCII and answering wrongly.
    ** The test is whether a codepoint has a case folding, not whether it is
    ** non-ASCII: a script without case has nothing to fold, so /#{'日本'}/i and the
    ** like are unaffected and stay out of the table.
    **
    ** U+017F and U+212A are out of the table as well, for the opposite reason:
    ** they fold to "s" and "k", so every build carries them and can answer.
    **
    ** Ranges are coarse. #{covered - refuse.size} uncased codepoints fall inside them and are
    ** refused too, which costs a pattern ASCII folding would have got right
    ** and buys a table a tenth the size of the mapping.
    **
    ** See Copyright Notice in mruby.h
    */

    /* Inclusive (lo, hi) pairs, ascending and disjoint. */
    static const uint32_t re_cased_ranges[][2] = {
  HEAD

  ranges.each do |lo, hi|
    out.puts "  { 0x%05X, 0x%05X }," % [lo, hi]
  end

  out.puts <<~TAIL
    };

    #define RE_CASED_RANGE_COUNT (sizeof(re_cased_ranges) / sizeof(re_cased_ranges[0]))

    /* Lowest and highest codepoint covered, so a lookup that cannot hit
       anything costs one comparison. */
    #define RE_CASED_MIN 0x#{'%05X' % ranges.first[0]}
    #define RE_CASED_MAX 0x#{'%05X' % ranges.last[1]}
  TAIL

  out.puts
  out.puts "/* #{refuse.size} cased codepoints in #{ranges.size} ranges spanning #{covered}. */"
end
