# The characters the differential test asks about.
#
# Generated by mrbgems/mruby-regexp/tools/difftest/gen_corpus.rb from the
# Unicode 17.0.0 character database. Do not edit by hand.
#
# One character out of every class the engine's tables tell apart, where a
# class is a whole signature and not one property at a time: the general
# category, the script, which POSIX types hold the character, the shape its
# case folding takes and the width the encoding spells it in. Each is the
# lowest codepoint of its signature no newer than Unicode 17.0,
# which is the release the CRuby the corpus is compared against carries, so
# that a character the two databases disagree about cannot be read as an
# engine that does. The whole of ASCII is taken as well, being what almost
# every pattern is written against.
#
# The comment beside each is its signature, spelled as
#
#   <general category> <script> <folding> w<width> <POSIX types>
#
# with the folding `C` a folding to one other character, `F` one that
# expands into several and `-` none, and one bit per POSIX type in this
# order:
#
#   alpha upper lower digit alnum word punct space blank graph print cntrl
#
# A codepoint taken for something other than its signature says so instead.
#
# See Copyright Notice in mruby.h

CORPUS = [
  0x0000,  # ascii
  0x0001,  # ascii
  0x0002,  # ascii
  0x0003,  # ascii
  0x0004,  # ascii
  0x0005,  # ascii
  0x0006,  # ascii
  0x0007,  # ascii
  0x0008,  # ascii
  0x0009,  # ascii
  0x000A,  # ascii
  0x000B,  # ascii
  0x000C,  # ascii
  0x000D,  # ascii
  0x000E,  # ascii
  0x000F,  # ascii
  0x0010,  # ascii
  0x0011,  # ascii
  0x0012,  # ascii
  0x0013,  # ascii
  0x0014,  # ascii
  0x0015,  # ascii
  0x0016,  # ascii
  0x0017,  # ascii
  0x0018,  # ascii
  0x0019,  # ascii
  0x001A,  # ascii
  0x001B,  # ascii
  0x001C,  # ascii
  0x001D,  # ascii
  0x001E,  # ascii
  0x001F,  # ascii
  0x0020,  # ascii
  0x0021,  # ascii
  0x0022,  # ascii
  0x0023,  # ascii
  0x0024,  # ascii
  0x0025,  # ascii
  0x0026,  # ascii
  0x0027,  # ascii
  0x0028,  # ascii
  0x0029,  # ascii
  0x002A,  # ascii
  0x002B,  # ascii
  0x002C,  # ascii
  0x002D,  # ascii
  0x002E,  # ascii
  0x002F,  # ascii
  0x0030,  # ascii
  0x0031,  # ascii
  0x0032,  # ascii
  0x0033,  # ascii
  0x0034,  # ascii
  0x0035,  # ascii
  0x0036,  # ascii
  0x0037,  # ascii
  0x0038,  # ascii
  0x0039,  # ascii
  0x003A,  # ascii
  0x003B,  # ascii
  0x003C,  # ascii
  0x003D,  # ascii
  0x003E,  # ascii
  0x003F,  # ascii
  0x0040,  # ascii
  0x0041,  # ascii
  0x0042,  # ascii
  0x0043,  # ascii
  0x0044,  # ascii
  0x0045,  # ascii
  0x0046,  # ascii
  0x0047,  # ascii
  0x0048,  # ascii
  0x0049,  # ascii
  0x004A,  # ascii
  0x004B,  # ascii
  0x004C,  # ascii
  0x004D,  # ascii
  0x004E,  # ascii
  0x004F,  # ascii
  0x0050,  # ascii
  0x0051,  # ascii
  0x0052,  # ascii
  0x0053,  # ascii
  0x0054,  # ascii
  0x0055,  # ascii
  0x0056,  # ascii
  0x0057,  # ascii
  0x0058,  # ascii
  0x0059,  # ascii
  0x005A,  # ascii
  0x005B,  # ascii
  0x005C,  # ascii
  0x005D,  # ascii
  0x005E,  # ascii
  0x005F,  # ascii
  0x0060,  # ascii
  0x0061,  # ascii
  0x0062,  # ascii
  0x0063,  # ascii
  0x0064,  # ascii
  0x0065,  # ascii
  0x0066,  # ascii
  0x0067,  # ascii
  0x0068,  # ascii
  0x0069,  # ascii
  0x006A,  # ascii
  0x006B,  # ascii
  0x006C,  # ascii
  0x006D,  # ascii
  0x006E,  # ascii
  0x006F,  # ascii
  0x0070,  # ascii
  0x0071,  # ascii
  0x0072,  # ascii
  0x0073,  # ascii
  0x0074,  # ascii
  0x0075,  # ascii
  0x0076,  # ascii
  0x0077,  # ascii
  0x0078,  # ascii
  0x0079,  # ascii
  0x007A,  # ascii
  0x007B,  # ascii
  0x007C,  # ascii
  0x007D,  # ascii
  0x007E,  # ascii
  0x007F,  # ascii
  0x0080,  # Cc Common - w2 000000000001
  0x0085,  # Cc Common - w2 000000010001
  0x00A0,  # Zs Common - w2 000000011010
  0x00A1,  # Po Common - w2 000000100110
  0x00A2,  # Sc Common - w2 000000000110
  0x00A6,  # So Common - w2 000000000110
  0x00A8,  # Sk Common - w2 000000000110
  0x00AA,  # Lo Latin - w2 101011000110
  0x00AB,  # Pi Common - w2 000000100110
  0x00AC,  # Sm Common - w2 000000000110
  0x00AD,  # Cf Common - w2 000000000110
  0x00B2,  # No Common - w2 000000000110
  0x00B5,  # Ll Common C w2 101011000110
  0x00BB,  # Pf Common - w2 000000100110
  0x00C0,  # Lu Latin C w2 110011000110
  0x00DF,  # Ll Latin F w2 101011000110
  0x00E0,  # Ll Latin - w2 101011000110
  0x0130,  # Lu Latin F w2 110011000110
  0x017F,  # Ll Latin C w2 101011000110
  0x01BB,  # Lo Latin - w2 100011000110
  0x01C5,  # Lt Latin C w2 100011000110
  0x02B0,  # Lm Latin - w2 101011000110
  0x02B9,  # Lm Common - w2 100011000110
  0x02C0,  # Lm Common - w2 101011000110
  0x02EA,  # Sk Bopomofo - w2 000000000110
  0x0300,  # Mn Inherited - w2 000001000110
  0x0345,  # Mn Inherited C w2 101011000110
  0x0363,  # Mn Inherited - w2 100011000110
  0x0370,  # Lu Greek C w2 110011000110
  0x0371,  # Ll Greek - w2 101011000110
  0x0375,  # Sk Greek - w2 000000000110
  0x037A,  # Lm Greek - w2 101011000110
  0x0390,  # Ll Greek F w2 101011000110
  0x03C2,  # Ll Greek C w2 101011000110
  0x03D2,  # Lu Greek - w2 110011000110
  0x03E2,  # Lu Coptic C w2 110011000110
  0x03E3,  # Ll Coptic - w2 101011000110
  0x03F6,  # Sm Greek - w2 000000000110
  0x0400,  # Lu Cyrillic C w2 110011000110
  0x0430,  # Ll Cyrillic - w2 101011000110
  0x0482,  # So Cyrillic - w2 000000000110
  0x0483,  # Mn Cyrillic - w2 000001000110
  0x0488,  # Me Cyrillic - w2 000001000110
  0x0531,  # Lu Armenian C w2 110011000110
  0x0559,  # Lm Armenian - w2 100011000110
  0x055A,  # Po Armenian - w2 000000100110
  0x0560,  # Ll Armenian - w2 101011000110
  0x0587,  # Ll Armenian F w2 101011000110
  0x058A,  # Pd Armenian - w2 000000100110
  0x058D,  # So Armenian - w2 000000000110
  0x058F,  # Sc Armenian - w2 000000000110
  0x0591,  # Mn Hebrew - w2 000001000110
  0x05B0,  # Mn Hebrew - w2 100011000110
  0x05BE,  # Pd Hebrew - w2 000000100110
  0x05C0,  # Po Hebrew - w2 000000100110
  0x05D0,  # Lo Hebrew - w2 100011000110
  0x0600,  # Cf Arabic - w2 000000000110
  0x0606,  # Sm Arabic - w2 000000000110
  0x0609,  # Po Arabic - w2 000000100110
  0x060B,  # Sc Arabic - w2 000000000110
  0x060E,  # So Arabic - w2 000000000110
  0x0610,  # Mn Arabic - w2 100011000110
  0x0620,  # Lo Arabic - w2 100011000110
  0x0658,  # Mn Arabic - w2 000001000110
  0x0660,  # Nd Arabic - w2 000111000110
  0x06E5,  # Lm Arabic - w2 100011000110
  0x0700,  # Po Syriac - w2 000000100110
  0x070F,  # Cf Syriac - w2 000000000110
  0x0710,  # Lo Syriac - w2 100011000110
  0x0711,  # Mn Syriac - w2 100011000110
  0x0740,  # Mn Syriac - w2 000001000110
  0x0780,  # Lo Thaana - w2 100011000110
  0x07A6,  # Mn Thaana - w2 100011000110
  0x07C0,  # Nd Nko - w2 000111000110
  0x07CA,  # Lo Nko - w2 100011000110
  0x07EB,  # Mn Nko - w2 000001000110
  0x07F4,  # Lm Nko - w2 100011000110
  0x07F6,  # So Nko - w2 000000000110
  0x07F7,  # Po Nko - w2 000000100110
  0x07FE,  # Sc Nko - w2 000000000110
  0x07FF,  # boundary
  0x0800,  # Lo Samaritan - w3 100011000110
  0x0816,  # Mn Samaritan - w3 100011000110
  0x0818,  # Mn Samaritan - w3 000001000110
  0x081A,  # Lm Samaritan - w3 100011000110
  0x0830,  # Po Samaritan - w3 000000100110
  0x0840,  # Lo Mandaic - w3 100011000110
  0x0859,  # Mn Mandaic - w3 000001000110
  0x085E,  # Po Mandaic - w3 000000100110
  0x0860,  # Lo Syriac - w3 100011000110
  0x0870,  # Lo Arabic - w3 100011000110
  0x0888,  # Sk Arabic - w3 000000000110
  0x0890,  # Cf Arabic - w3 000000000110
  0x0897,  # Mn Arabic - w3 100011000110
  0x0898,  # Mn Arabic - w3 000001000110
  0x08C9,  # Lm Arabic - w3 100011000110
  0x08E2,  # Cf Common - w3 000000000110
  0x0900,  # Mn Devanagari - w3 100011000110
  0x0903,  # Mc Devanagari - w3 100011000110
  0x0904,  # Lo Devanagari - w3 100011000110
  0x093C,  # Mn Devanagari - w3 000001000110
  0x0951,  # Mn Inherited - w3 000001000110
  0x0964,  # Po Common - w3 000000100110
  0x0966,  # Nd Devanagari - w3 000111000110
  0x0970,  # Po Devanagari - w3 000000100110
  0x0971,  # Lm Devanagari - w3 100011000110
  0x0980,  # Lo Bengali - w3 100011000110
  0x0981,  # Mn Bengali - w3 100011000110
  0x0982,  # Mc Bengali - w3 100011000110
  0x09BC,  # Mn Bengali - w3 000001000110
  0x09E6,  # Nd Bengali - w3 000111000110
  0x09F2,  # Sc Bengali - w3 000000000110
  0x09F4,  # No Bengali - w3 000000000110
  0x09FA,  # So Bengali - w3 000000000110
  0x09FD,  # Po Bengali - w3 000000100110
  0x0A01,  # Mn Gurmukhi - w3 100011000110
  0x0A03,  # Mc Gurmukhi - w3 100011000110
  0x0A05,  # Lo Gurmukhi - w3 100011000110
  0x0A3C,  # Mn Gurmukhi - w3 000001000110
  0x0A66,  # Nd Gurmukhi - w3 000111000110
  0x0A76,  # Po Gurmukhi - w3 000000100110
  0x0A81,  # Mn Gujarati - w3 100011000110
  0x0A83,  # Mc Gujarati - w3 100011000110
  0x0A85,  # Lo Gujarati - w3 100011000110
  0x0ABC,  # Mn Gujarati - w3 000001000110
  0x0AE6,  # Nd Gujarati - w3 000111000110
  0x0AF0,  # Po Gujarati - w3 000000100110
  0x0AF1,  # Sc Gujarati - w3 000000000110
  0x0B01,  # Mn Oriya - w3 100011000110
  0x0B02,  # Mc Oriya - w3 100011000110
  0x0B05,  # Lo Oriya - w3 100011000110
  0x0B3C,  # Mn Oriya - w3 000001000110
  0x0B66,  # Nd Oriya - w3 000111000110
  0x0B70,  # So Oriya - w3 000000000110
  0x0B72,  # No Oriya - w3 000000000110
  0x0B82,  # Mn Tamil - w3 100011000110
  0x0B83,  # Lo Tamil - w3 100011000110
  0x0BBE,  # Mc Tamil - w3 100011000110
  0x0BCD,  # Mn Tamil - w3 000001000110
  0x0BE6,  # Nd Tamil - w3 000111000110
  0x0BF0,  # No Tamil - w3 000000000110
  0x0BF3,  # So Tamil - w3 000000000110
  0x0BF9,  # Sc Tamil - w3 000000000110
  0x0C00,  # Mn Telugu - w3 100011000110
  0x0C01,  # Mc Telugu - w3 100011000110
  0x0C05,  # Lo Telugu - w3 100011000110
  0x0C3C,  # Mn Telugu - w3 000001000110
  0x0C66,  # Nd Telugu - w3 000111000110
  0x0C77,  # Po Telugu - w3 000000100110
  0x0C78,  # No Telugu - w3 000000000110
  0x0C7F,  # So Telugu - w3 000000000110
  0x0C80,  # Lo Kannada - w3 100011000110
  0x0C81,  # Mn Kannada - w3 100011000110
  0x0C82,  # Mc Kannada - w3 100011000110
  0x0C84,  # Po Kannada - w3 000000100110
  0x0CBC,  # Mn Kannada - w3 000001000110
  0x0CE6,  # Nd Kannada - w3 000111000110
  0x0D00,  # Mn Malayalam - w3 100011000110
  0x0D02,  # Mc Malayalam - w3 100011000110
  0x0D04,  # Lo Malayalam - w3 100011000110
  0x0D3B,  # Mn Malayalam - w3 000001000110
  0x0D4F,  # So Malayalam - w3 000000000110
  0x0D58,  # No Malayalam - w3 000000000110
  0x0D66,  # Nd Malayalam - w3 000111000110
  0x0D81,  # Mn Sinhala - w3 100011000110
  0x0D82,  # Mc Sinhala - w3 100011000110
  0x0D85,  # Lo Sinhala - w3 100011000110
  0x0DCA,  # Mn Sinhala - w3 000001000110
  0x0DE6,  # Nd Sinhala - w3 000111000110
  0x0DF4,  # Po Sinhala - w3 000000100110
  0x0E01,  # Lo Thai - w3 100011000110
  0x0E31,  # Mn Thai - w3 100011000110
  0x0E3F,  # Sc Common - w3 000000000110
  0x0E46,  # Lm Thai - w3 100011000110
  0x0E47,  # Mn Thai - w3 000001000110
  0x0E4F,  # Po Thai - w3 000000100110
  0x0E50,  # Nd Thai - w3 000111000110
  0x0E81,  # Lo Lao - w3 100011000110
  0x0EB1,  # Mn Lao - w3 100011000110
  0x0EBA,  # Mn Lao - w3 000001000110
  0x0EC6,  # Lm Lao - w3 100011000110
  0x0ED0,  # Nd Lao - w3 000111000110
  0x0F00,  # Lo Tibetan - w3 100011000110
  0x0F01,  # So Tibetan - w3 000000000110
  0x0F04,  # Po Tibetan - w3 000000100110
  0x0F18,  # Mn Tibetan - w3 000001000110
  0x0F20,  # Nd Tibetan - w3 000111000110
  0x0F2A,  # No Tibetan - w3 000000000110
  0x0F3A,  # Ps Tibetan - w3 000000100110
  0x0F3B,  # Pe Tibetan - w3 000000100110
  0x0F3E,  # Mc Tibetan - w3 000001000110
  0x0F71,  # Mn Tibetan - w3 100011000110
  0x0F7F,  # Mc Tibetan - w3 100011000110
  0x0FD5,  # So Common - w3 000000000110
  0x1000,  # Lo Myanmar - w3 100011000110
  0x102B,  # Mc Myanmar - w3 100011000110
  0x102D,  # Mn Myanmar - w3 100011000110
  0x1037,  # Mn Myanmar - w3 000001000110
  0x1040,  # Nd Myanmar - w3 000111000110
  0x104A,  # Po Myanmar - w3 000000100110
  0x109E,  # So Myanmar - w3 000000000110
  0x10A0,  # Lu Georgian C w3 110011000110
  0x10D0,  # Ll Georgian - w3 101011000110
  0x10FC,  # Lm Georgian - w3 101011000110
  0x1100,  # Lo Hangul - w3 100011000110
  0x1200,  # Lo Ethiopic - w3 100011000110
  0x135D,  # Mn Ethiopic - w3 000001000110
  0x1360,  # Po Ethiopic - w3 000000100110
  0x1369,  # No Ethiopic - w3 000000000110
  0x1390,  # So Ethiopic - w3 000000000110
  0x13A0,  # Lu Cherokee - w3 110011000110
  0x13F8,  # Ll Cherokee C w3 101011000110
  0x1400,  # Pd Canadian_Aboriginal - w3 000000100110
  0x1401,  # Lo Canadian_Aboriginal - w3 100011000110
  0x166D,  # So Canadian_Aboriginal - w3 000000000110
  0x166E,  # Po Canadian_Aboriginal - w3 000000100110
  0x1680,  # Zs Ogham - w3 000000011010
  0x1681,  # Lo Ogham - w3 100011000110
  0x169B,  # Ps Ogham - w3 000000100110
  0x169C,  # Pe Ogham - w3 000000100110
  0x16A0,  # Lo Runic - w3 100011000110
  0x16EE,  # Nl Runic - w3 100011000110
  0x1700,  # Lo Tagalog - w3 100011000110
  0x1712,  # Mn Tagalog - w3 100011000110
  0x1714,  # Mn Tagalog - w3 000001000110
  0x1715,  # Mc Tagalog - w3 000001000110
  0x1720,  # Lo Hanunoo - w3 100011000110
  0x1732,  # Mn Hanunoo - w3 100011000110
  0x1734,  # Mc Hanunoo - w3 000001000110
  0x1740,  # Lo Buhid - w3 100011000110
  0x1752,  # Mn Buhid - w3 100011000110
  0x1760,  # Lo Tagbanwa - w3 100011000110
  0x1772,  # Mn Tagbanwa - w3 100011000110
  0x1780,  # Lo Khmer - w3 100011000110
  0x17B4,  # Mn Khmer - w3 000001000110
  0x17B6,  # Mc Khmer - w3 100011000110
  0x17B7,  # Mn Khmer - w3 100011000110
  0x17D4,  # Po Khmer - w3 000000100110
  0x17D7,  # Lm Khmer - w3 100011000110
  0x17DB,  # Sc Khmer - w3 000000000110
  0x17E0,  # Nd Khmer - w3 000111000110
  0x17F0,  # No Khmer - w3 000000000110
  0x1800,  # Po Mongolian - w3 000000100110
  0x1806,  # Pd Mongolian - w3 000000100110
  0x180B,  # Mn Mongolian - w3 000001000110
  0x180E,  # Cf Mongolian - w3 000000000110
  0x1810,  # Nd Mongolian - w3 000111000110
  0x1820,  # Lo Mongolian - w3 100011000110
  0x1843,  # Lm Mongolian - w3 100011000110
  0x1885,  # Mn Mongolian - w3 100011000110
  0x1900,  # Lo Limbu - w3 100011000110
  0x1920,  # Mn Limbu - w3 100011000110
  0x1923,  # Mc Limbu - w3 100011000110
  0x1939,  # Mn Limbu - w3 000001000110
  0x1940,  # So Limbu - w3 000000000110
  0x1944,  # Po Limbu - w3 000000100110
  0x1946,  # Nd Limbu - w3 000111000110
  0x1950,  # Lo Tai_Le - w3 100011000110
  0x1980,  # Lo New_Tai_Lue - w3 100011000110
  0x19D0,  # Nd New_Tai_Lue - w3 000111000110
  0x19DA,  # No New_Tai_Lue - w3 000000000110
  0x19DE,  # So New_Tai_Lue - w3 000000000110
  0x19E0,  # So Khmer - w3 000000000110
  0x1A00,  # Lo Buginese - w3 100011000110
  0x1A17,  # Mn Buginese - w3 100011000110
  0x1A19,  # Mc Buginese - w3 100011000110
  0x1A1E,  # Po Buginese - w3 000000100110
  0x1A20,  # Lo Tai_Tham - w3 100011000110
  0x1A55,  # Mc Tai_Tham - w3 100011000110
  0x1A56,  # Mn Tai_Tham - w3 100011000110
  0x1A60,  # Mn Tai_Tham - w3 000001000110
  0x1A80,  # Nd Tai_Tham - w3 000111000110
  0x1AA0,  # Po Tai_Tham - w3 000000100110
  0x1AA7,  # Lm Tai_Tham - w3 100011000110
  0x1ABE,  # Me Inherited - w3 000001000110
  0x1ABF,  # Mn Inherited - w3 100011000110
  0x1B00,  # Mn Balinese - w3 100011000110
  0x1B04,  # Mc Balinese - w3 100011000110
  0x1B05,  # Lo Balinese - w3 100011000110
  0x1B34,  # Mn Balinese - w3 000001000110
  0x1B44,  # Mc Balinese - w3 000001000110
  0x1B4E,  # Po Balinese - w3 000000100110
  0x1B50,  # Nd Balinese - w3 000111000110
  0x1B61,  # So Balinese - w3 000000000110
  0x1B80,  # Mn Sundanese - w3 100011000110
  0x1B82,  # Mc Sundanese - w3 100011000110
  0x1B83,  # Lo Sundanese - w3 100011000110
  0x1BAA,  # Mc Sundanese - w3 000001000110
  0x1BAB,  # Mn Sundanese - w3 000001000110
  0x1BB0,  # Nd Sundanese - w3 000111000110
  0x1BC0,  # Lo Batak - w3 100011000110
  0x1BE6,  # Mn Batak - w3 000001000110
  0x1BE7,  # Mc Batak - w3 100011000110
  0x1BE8,  # Mn Batak - w3 100011000110
  0x1BF2,  # Mc Batak - w3 000001000110
  0x1BFC,  # Po Batak - w3 000000100110
  0x1C00,  # Lo Lepcha - w3 100011000110
  0x1C24,  # Mc Lepcha - w3 100011000110
  0x1C2C,  # Mn Lepcha - w3 100011000110
  0x1C37,  # Mn Lepcha - w3 000001000110
  0x1C3B,  # Po Lepcha - w3 000000100110
  0x1C40,  # Nd Lepcha - w3 000111000110
  0x1C50,  # Nd Ol_Chiki - w3 000111000110
  0x1C5A,  # Lo Ol_Chiki - w3 100011000110
  0x1C78,  # Lm Ol_Chiki - w3 100011000110
  0x1C7E,  # Po Ol_Chiki - w3 000000100110
  0x1C80,  # Ll Cyrillic C w3 101011000110
  0x1C89,  # Lu Cyrillic C w3 110011000110
  0x1C8A,  # Ll Cyrillic - w3 101011000110
  0x1CC0,  # Po Sundanese - w3 000000100110
  0x1CE1,  # Mc Common - w3 000001000110
  0x1CE9,  # Lo Common - w3 100011000110
  0x1D00,  # Ll Latin - w3 101011000110
  0x1D26,  # Ll Greek - w3 101011000110
  0x1D2C,  # Lm Latin - w3 101011000110
  0x1D5D,  # Lm Greek - w3 101011000110
  0x1D78,  # Lm Cyrillic - w3 101011000110
  0x1E00,  # Lu Latin C w3 110011000110
  0x1E96,  # Ll Latin F w3 101011000110
  0x1E9B,  # Ll Latin C w3 101011000110
  0x1E9E,  # Lu Latin F w3 110011000110
  0x1F08,  # Lu Greek C w3 110011000110
  0x1F50,  # Ll Greek F w3 101011000110
  0x1F88,  # Lt Greek F w3 100011000110
  0x1FBD,  # Sk Greek - w3 000000000110
  0x1FBE,  # Ll Greek C w3 101011000110
  0x2000,  # Zs Common - w3 000000011010
  0x200C,  # Cf Inherited - w3 000001000110
  0x2010,  # Pd Common - w3 000000100110
  0x2018,  # Pi Common - w3 000000100110
  0x2019,  # Pf Common - w3 000000100110
  0x201A,  # Ps Common - w3 000000100110
  0x2028,  # Zl Common - w3 000000010000
  0x2029,  # Zp Common - w3 000000010000
  0x203F,  # Pc Common - w3 000001100110
  0x2044,  # Sm Common - w3 000000000110
  0x2046,  # Pe Common - w3 000000100110
  0x2070,  # No Common - w3 000000000110
  0x2102,  # Lu Common - w3 110011000110
  0x210A,  # Ll Common - w3 101011000110
  0x212A,  # folds to ASCII
  0x2160,  # Nl Latin C w3 110011000110
  0x2170,  # Nl Latin - w3 101011000110
  0x2180,  # Nl Latin - w3 100011000110
  0x24B6,  # So Common C w3 110011000110
  0x24D0,  # So Common - w3 101011000110
  0x2800,  # So Braille - w3 000000000110
  0x2C00,  # Lu Glagolitic C w3 110011000110
  0x2C30,  # Ll Glagolitic - w3 101011000110
  0x2C80,  # Lu Coptic C w3 110011000110
  0x2C81,  # Ll Coptic - w3 101011000110
  0x2CE5,  # So Coptic - w3 000000000110
  0x2CEF,  # Mn Coptic - w3 000001000110
  0x2CF9,  # Po Coptic - w3 000000100110
  0x2CFD,  # No Coptic - w3 000000000110
  0x2D30,  # Lo Tifinagh - w3 100011000110
  0x2D6F,  # Lm Tifinagh - w3 100011000110
  0x2D70,  # Po Tifinagh - w3 000000100110
  0x2D7F,  # Mn Tifinagh - w3 000001000110
  0x2DE0,  # Mn Cyrillic - w3 100011000110
  0x2E2F,  # Lm Common - w3 100011000110
  0x2E80,  # So Han - w3 000000000110
  0x3005,  # Lm Han - w3 100011000110
  0x3007,  # Nl Han - w3 100011000110
  0x302E,  # Mc Hangul - w3 000001000110
  0x3041,  # Lo Hiragana - w3 100011000110
  0x309B,  # Sk Common - w3 000000000110
  0x309D,  # Lm Hiragana - w3 100011000110
  0x30A1,  # Lo Katakana - w3 100011000110
  0x30FD,  # Lm Katakana - w3 100011000110
  0x3105,  # Lo Bopomofo - w3 100011000110
  0x3200,  # So Hangul - w3 000000000110
  0x32D0,  # So Katakana - w3 000000000110
  0x3400,  # Lo Han - w3 100011000110
  0xA000,  # Lo Yi - w3 100011000110
  0xA015,  # Lm Yi - w3 100011000110
  0xA490,  # So Yi - w3 000000000110
  0xA4D0,  # Lo Lisu - w3 100011000110
  0xA4F8,  # Lm Lisu - w3 100011000110
  0xA4FE,  # Po Lisu - w3 000000100110
  0xA500,  # Lo Vai - w3 100011000110
  0xA60C,  # Lm Vai - w3 100011000110
  0xA60D,  # Po Vai - w3 000000100110
  0xA620,  # Nd Vai - w3 000111000110
  0xA66E,  # Lo Cyrillic - w3 100011000110
  0xA66F,  # Mn Cyrillic - w3 000001000110
  0xA670,  # Me Cyrillic - w3 000001000110
  0xA673,  # Po Cyrillic - w3 000000100110
  0xA67F,  # Lm Cyrillic - w3 100011000110
  0xA6A0,  # Lo Bamum - w3 100011000110
  0xA6E6,  # Nl Bamum - w3 100011000110
  0xA6F0,  # Mn Bamum - w3 000001000110
  0xA6F2,  # Po Bamum - w3 000000100110
  0xA78F,  # Lo Latin - w3 100011000110
  0xA800,  # Lo Syloti_Nagri - w3 100011000110
  0xA802,  # Mn Syloti_Nagri - w3 100011000110
  0xA806,  # Mn Syloti_Nagri - w3 000001000110
  0xA823,  # Mc Syloti_Nagri - w3 100011000110
  0xA828,  # So Syloti_Nagri - w3 000000000110
  0xA840,  # Lo Phags_Pa - w3 100011000110
  0xA874,  # Po Phags_Pa - w3 000000100110
  0xA880,  # Mc Saurashtra - w3 100011000110
  0xA882,  # Lo Saurashtra - w3 100011000110
  0xA8C4,  # Mn Saurashtra - w3 000001000110
  0xA8C5,  # Mn Saurashtra - w3 100011000110
  0xA8CE,  # Po Saurashtra - w3 000000100110
  0xA8D0,  # Nd Saurashtra - w3 000111000110
  0xA900,  # Nd Kayah_Li - w3 000111000110
  0xA90A,  # Lo Kayah_Li - w3 100011000110
  0xA926,  # Mn Kayah_Li - w3 100011000110
  0xA92B,  # Mn Kayah_Li - w3 000001000110
  0xA92F,  # Po Kayah_Li - w3 000000100110
  0xA930,  # Lo Rejang - w3 100011000110
  0xA947,  # Mn Rejang - w3 100011000110
  0xA952,  # Mc Rejang - w3 100011000110
  0xA953,  # Mc Rejang - w3 000001000110
  0xA95F,  # Po Rejang - w3 000000100110
  0xA980,  # Mn Javanese - w3 100011000110
  0xA983,  # Mc Javanese - w3 100011000110
  0xA984,  # Lo Javanese - w3 100011000110
  0xA9B3,  # Mn Javanese - w3 000001000110
  0xA9C0,  # Mc Javanese - w3 000001000110
  0xA9C1,  # Po Javanese - w3 000000100110
  0xA9D0,  # Nd Javanese - w3 000111000110
  0xA9E6,  # Lm Myanmar - w3 100011000110
  0xAA00,  # Lo Cham - w3 100011000110
  0xAA29,  # Mn Cham - w3 100011000110
  0xAA2F,  # Mc Cham - w3 100011000110
  0xAA50,  # Nd Cham - w3 000111000110
  0xAA5C,  # Po Cham - w3 000000100110
  0xAA80,  # Lo Tai_Viet - w3 100011000110
  0xAAB0,  # Mn Tai_Viet - w3 100011000110
  0xAABF,  # Mn Tai_Viet - w3 000001000110
  0xAADD,  # Lm Tai_Viet - w3 100011000110
  0xAADE,  # Po Tai_Viet - w3 000000100110
  0xAAE0,  # Lo Meetei_Mayek - w3 100011000110
  0xAAEB,  # Mc Meetei_Mayek - w3 100011000110
  0xAAEC,  # Mn Meetei_Mayek - w3 100011000110
  0xAAF0,  # Po Meetei_Mayek - w3 000000100110
  0xAAF3,  # Lm Meetei_Mayek - w3 100011000110
  0xAAF6,  # Mn Meetei_Mayek - w3 000001000110
  0xABEC,  # Mc Meetei_Mayek - w3 000001000110
  0xABF0,  # Nd Meetei_Mayek - w3 000111000110
  0xD7FF,  # boundary
  0xD800,  # Cs Unknown - w3 000000000000
  0xE000,  # Co Unknown - w3 000000000110
  0xFB13,  # Ll Armenian F w3 101011000110
  0xFB1D,  # Lo Hebrew - w3 100011000110
  0xFB1E,  # Mn Hebrew - w3 100011000110
  0xFB29,  # Sm Hebrew - w3 000000000110
  0xFBC3,  # So Arabic - w3 000000000110
  0xFDD0,  # Cn Unknown - w3 000000000000
  0xFDFC,  # Sc Arabic - w3 000000000110
  0xFF10,  # Nd Common - w3 000111000110
  0xFFFF,  # boundary
  0x10000,  # Lo Linear_B - w4 100011000110
  0x10100,  # Po Common - w4 000000100110
  0x10107,  # No Common - w4 000000000110
  0x10137,  # So Common - w4 000000000110
  0x10140,  # Nl Greek - w4 100011000110
  0x10175,  # No Greek - w4 000000000110
  0x10179,  # So Greek - w4 000000000110
  0x101FD,  # Mn Inherited - w4 000001000110
  0x10280,  # Lo Lycian - w4 100011000110
  0x102A0,  # Lo Carian - w4 100011000110
  0x10300,  # Lo Old_Italic - w4 100011000110
  0x10320,  # No Old_Italic - w4 000000000110
  0x10330,  # Lo Gothic - w4 100011000110
  0x10341,  # Nl Gothic - w4 100011000110
  0x10350,  # Lo Old_Permic - w4 100011000110
  0x10376,  # Mn Old_Permic - w4 100011000110
  0x10380,  # Lo Ugaritic - w4 100011000110
  0x1039F,  # Po Ugaritic - w4 000000100110
  0x103A0,  # Lo Old_Persian - w4 100011000110
  0x103D0,  # Po Old_Persian - w4 000000100110
  0x103D1,  # Nl Old_Persian - w4 100011000110
  0x10400,  # Lu Deseret C w4 110011000110
  0x10428,  # Ll Deseret - w4 101011000110
  0x10450,  # Lo Shavian - w4 100011000110
  0x10480,  # Lo Osmanya - w4 100011000110
  0x104A0,  # Nd Osmanya - w4 000111000110
  0x104B0,  # Lu Osage C w4 110011000110
  0x104D8,  # Ll Osage - w4 101011000110
  0x10500,  # Lo Elbasan - w4 100011000110
  0x10530,  # Lo Caucasian_Albanian - w4 100011000110
  0x1056F,  # Po Caucasian_Albanian - w4 000000100110
  0x10570,  # Lu Vithkuqi C w4 110011000110
  0x10597,  # Ll Vithkuqi - w4 101011000110
  0x105C0,  # Lo Todhri - w4 100011000110
  0x10600,  # Lo Linear_A - w4 100011000110
  0x10780,  # Lm Latin - w4 101011000110
  0x10781,  # Lm Latin - w4 100011000110
  0x10800,  # Lo Cypriot - w4 100011000110
  0x10840,  # Lo Imperial_Aramaic - w4 100011000110
  0x10857,  # Po Imperial_Aramaic - w4 000000100110
  0x10858,  # No Imperial_Aramaic - w4 000000000110
  0x10860,  # Lo Palmyrene - w4 100011000110
  0x10877,  # So Palmyrene - w4 000000000110
  0x10879,  # No Palmyrene - w4 000000000110
  0x10880,  # Lo Nabataean - w4 100011000110
  0x108A7,  # No Nabataean - w4 000000000110
  0x108E0,  # Lo Hatran - w4 100011000110
  0x108FB,  # No Hatran - w4 000000000110
  0x10900,  # Lo Phoenician - w4 100011000110
  0x10916,  # No Phoenician - w4 000000000110
  0x1091F,  # Po Phoenician - w4 000000100110
  0x10920,  # Lo Lydian - w4 100011000110
  0x1093F,  # Po Lydian - w4 000000100110
  0x10940,  # Lo Sidetic - w4 100011000110
  0x10980,  # Lo Meroitic_Hieroglyphs - w4 100011000110
  0x109A0,  # Lo Meroitic_Cursive - w4 100011000110
  0x109BC,  # No Meroitic_Cursive - w4 000000000110
  0x10A00,  # Lo Kharoshthi - w4 100011000110
  0x10A01,  # Mn Kharoshthi - w4 100011000110
  0x10A38,  # Mn Kharoshthi - w4 000001000110
  0x10A40,  # No Kharoshthi - w4 000000000110
  0x10A50,  # Po Kharoshthi - w4 000000100110
  0x10A60,  # Lo Old_South_Arabian - w4 100011000110
  0x10A7D,  # No Old_South_Arabian - w4 000000000110
  0x10A7F,  # Po Old_South_Arabian - w4 000000100110
  0x10A80,  # Lo Old_North_Arabian - w4 100011000110
  0x10A9D,  # No Old_North_Arabian - w4 000000000110
  0x10AC0,  # Lo Manichaean - w4 100011000110
  0x10AC8,  # So Manichaean - w4 000000000110
  0x10AE5,  # Mn Manichaean - w4 000001000110
  0x10AEB,  # No Manichaean - w4 000000000110
  0x10AF0,  # Po Manichaean - w4 000000100110
  0x10B00,  # Lo Avestan - w4 100011000110
  0x10B39,  # Po Avestan - w4 000000100110
  0x10B40,  # Lo Inscriptional_Parthian - w4 100011000110
  0x10B58,  # No Inscriptional_Parthian - w4 000000000110
  0x10B60,  # Lo Inscriptional_Pahlavi - w4 100011000110
  0x10B78,  # No Inscriptional_Pahlavi - w4 000000000110
  0x10B80,  # Lo Psalter_Pahlavi - w4 100011000110
  0x10B99,  # Po Psalter_Pahlavi - w4 000000100110
  0x10BA9,  # No Psalter_Pahlavi - w4 000000000110
  0x10C00,  # Lo Old_Turkic - w4 100011000110
  0x10C80,  # Lu Old_Hungarian C w4 110011000110
  0x10CC0,  # Ll Old_Hungarian - w4 101011000110
  0x10CFA,  # No Old_Hungarian - w4 000000000110
  0x10D00,  # Lo Hanifi_Rohingya - w4 100011000110
  0x10D24,  # Mn Hanifi_Rohingya - w4 100011000110
  0x10D30,  # Nd Hanifi_Rohingya - w4 000111000110
  0x10D40,  # Nd Garay - w4 000111000110
  0x10D4A,  # Lo Garay - w4 100011000110
  0x10D4E,  # Lm Garay - w4 100011000110
  0x10D50,  # Lu Garay C w4 110011000110
  0x10D69,  # Mn Garay - w4 100011000110
  0x10D6A,  # Mn Garay - w4 000001000110
  0x10D6E,  # Pd Garay - w4 000000100110
  0x10D70,  # Ll Garay - w4 101011000110
  0x10D8E,  # Sm Garay - w4 000000000110
  0x10E60,  # No Arabic - w4 000000000110
  0x10E80,  # Lo Yezidi - w4 100011000110
  0x10EAB,  # Mn Yezidi - w4 100011000110
  0x10EAD,  # Pd Yezidi - w4 000000100110
  0x10EC2,  # Lo Arabic - w4 100011000110
  0x10EC5,  # Lm Arabic - w4 100011000110
  0x10ED0,  # Po Arabic - w4 000000100110
  0x10ED1,  # So Arabic - w4 000000000110
  0x10EFA,  # Mn Arabic - w4 100011000110
  0x10EFD,  # Mn Arabic - w4 000001000110
  0x10F00,  # Lo Old_Sogdian - w4 100011000110
  0x10F1D,  # No Old_Sogdian - w4 000000000110
  0x10F30,  # Lo Sogdian - w4 100011000110
  0x10F46,  # Mn Sogdian - w4 000001000110
  0x10F51,  # No Sogdian - w4 000000000110
  0x10F55,  # Po Sogdian - w4 000000100110
  0x10F70,  # Lo Old_Uyghur - w4 100011000110
  0x10F82,  # Mn Old_Uyghur - w4 000001000110
  0x10F86,  # Po Old_Uyghur - w4 000000100110
  0x10FB0,  # Lo Chorasmian - w4 100011000110
  0x10FC5,  # No Chorasmian - w4 000000000110
  0x10FE0,  # Lo Elymaic - w4 100011000110
  0x11000,  # Mc Brahmi - w4 100011000110
  0x11001,  # Mn Brahmi - w4 100011000110
  0x11003,  # Lo Brahmi - w4 100011000110
  0x11046,  # Mn Brahmi - w4 000001000110
  0x11047,  # Po Brahmi - w4 000000100110
  0x11052,  # No Brahmi - w4 000000000110
  0x11066,  # Nd Brahmi - w4 000111000110
  0x11080,  # Mn Kaithi - w4 100011000110
  0x11082,  # Mc Kaithi - w4 100011000110
  0x11083,  # Lo Kaithi - w4 100011000110
  0x110B9,  # Mn Kaithi - w4 000001000110
  0x110BB,  # Po Kaithi - w4 000000100110
  0x110BD,  # Cf Kaithi - w4 000000000110
  0x110D0,  # Lo Sora_Sompeng - w4 100011000110
  0x110F0,  # Nd Sora_Sompeng - w4 000111000110
  0x11100,  # Mn Chakma - w4 100011000110
  0x11103,  # Lo Chakma - w4 100011000110
  0x1112C,  # Mc Chakma - w4 100011000110
  0x11133,  # Mn Chakma - w4 000001000110
  0x11136,  # Nd Chakma - w4 000111000110
  0x11140,  # Po Chakma - w4 000000100110
  0x11150,  # Lo Mahajani - w4 100011000110
  0x11173,  # Mn Mahajani - w4 000001000110
  0x11174,  # Po Mahajani - w4 000000100110
  0x11180,  # Mn Sharada - w4 100011000110
  0x11182,  # Mc Sharada - w4 100011000110
  0x11183,  # Lo Sharada - w4 100011000110
  0x111C0,  # Mc Sharada - w4 000001000110
  0x111C5,  # Po Sharada - w4 000000100110
  0x111C9,  # Mn Sharada - w4 000001000110
  0x111D0,  # Nd Sharada - w4 000111000110
  0x111E1,  # No Sinhala - w4 000000000110
  0x11200,  # Lo Khojki - w4 100011000110
  0x1122C,  # Mc Khojki - w4 100011000110
  0x1122F,  # Mn Khojki - w4 100011000110
  0x11235,  # Mc Khojki - w4 000001000110
  0x11236,  # Mn Khojki - w4 000001000110
  0x11238,  # Po Khojki - w4 000000100110
  0x11280,  # Lo Multani - w4 100011000110
  0x112A9,  # Po Multani - w4 000000100110
  0x112B0,  # Lo Khudawadi - w4 100011000110
  0x112DF,  # Mn Khudawadi - w4 100011000110
  0x112E0,  # Mc Khudawadi - w4 100011000110
  0x112E9,  # Mn Khudawadi - w4 000001000110
  0x112F0,  # Nd Khudawadi - w4 000111000110
  0x11300,  # Mn Grantha - w4 100011000110
  0x11302,  # Mc Grantha - w4 100011000110
  0x11305,  # Lo Grantha - w4 100011000110
  0x1133C,  # Mn Grantha - w4 000001000110
  0x1134D,  # Mc Grantha - w4 000001000110
  0x11380,  # Lo Tulu_Tigalari - w4 100011000110
  0x113B8,  # Mc Tulu_Tigalari - w4 100011000110
  0x113BB,  # Mn Tulu_Tigalari - w4 100011000110
  0x113CE,  # Mn Tulu_Tigalari - w4 000001000110
  0x113CF,  # Mc Tulu_Tigalari - w4 000001000110
  0x113D4,  # Po Tulu_Tigalari - w4 000000100110
  0x11400,  # Lo Newa - w4 100011000110
  0x11435,  # Mc Newa - w4 100011000110
  0x11438,  # Mn Newa - w4 100011000110
  0x11442,  # Mn Newa - w4 000001000110
  0x1144B,  # Po Newa - w4 000000100110
  0x11450,  # Nd Newa - w4 000111000110
  0x11480,  # Lo Tirhuta - w4 100011000110
  0x114B0,  # Mc Tirhuta - w4 100011000110
  0x114B3,  # Mn Tirhuta - w4 100011000110
  0x114C2,  # Mn Tirhuta - w4 000001000110
  0x114C6,  # Po Tirhuta - w4 000000100110
  0x114D0,  # Nd Tirhuta - w4 000111000110
  0x11580,  # Lo Siddham - w4 100011000110
  0x115AF,  # Mc Siddham - w4 100011000110
  0x115B2,  # Mn Siddham - w4 100011000110
  0x115BF,  # Mn Siddham - w4 000001000110
  0x115C1,  # Po Siddham - w4 000000100110
  0x11600,  # Lo Modi - w4 100011000110
  0x11630,  # Mc Modi - w4 100011000110
  0x11633,  # Mn Modi - w4 100011000110
  0x1163F,  # Mn Modi - w4 000001000110
  0x11641,  # Po Modi - w4 000000100110
  0x11650,  # Nd Modi - w4 000111000110
  0x11660,  # Po Mongolian - w4 000000100110
  0x11680,  # Lo Takri - w4 100011000110
  0x116AB,  # Mn Takri - w4 100011000110
  0x116AC,  # Mc Takri - w4 100011000110
  0x116B6,  # Mc Takri - w4 000001000110
  0x116B7,  # Mn Takri - w4 000001000110
  0x116B9,  # Po Takri - w4 000000100110
  0x116C0,  # Nd Takri - w4 000111000110
  0x116D0,  # Nd Myanmar - w4 000111000110
  0x11700,  # Lo Ahom - w4 100011000110
  0x1171D,  # Mn Ahom - w4 100011000110
  0x1171E,  # Mc Ahom - w4 100011000110
  0x1172B,  # Mn Ahom - w4 000001000110
  0x11730,  # Nd Ahom - w4 000111000110
  0x1173A,  # No Ahom - w4 000000000110
  0x1173C,  # Po Ahom - w4 000000100110
  0x1173F,  # So Ahom - w4 000000000110
  0x11800,  # Lo Dogra - w4 100011000110
  0x1182C,  # Mc Dogra - w4 100011000110
  0x1182F,  # Mn Dogra - w4 100011000110
  0x11839,  # Mn Dogra - w4 000001000110
  0x1183B,  # Po Dogra - w4 000000100110
  0x118A0,  # Lu Warang_Citi C w4 110011000110
  0x118C0,  # Ll Warang_Citi - w4 101011000110
  0x118E0,  # Nd Warang_Citi - w4 000111000110
  0x118EA,  # No Warang_Citi - w4 000000000110
  0x118FF,  # Lo Warang_Citi - w4 100011000110
  0x11900,  # Lo Dives_Akuru - w4 100011000110
  0x11930,  # Mc Dives_Akuru - w4 100011000110
  0x1193B,  # Mn Dives_Akuru - w4 100011000110
  0x1193D,  # Mc Dives_Akuru - w4 000001000110
  0x1193E,  # Mn Dives_Akuru - w4 000001000110
  0x11944,  # Po Dives_Akuru - w4 000000100110
  0x11950,  # Nd Dives_Akuru - w4 000111000110
  0x119A0,  # Lo Nandinagari - w4 100011000110
  0x119D1,  # Mc Nandinagari - w4 100011000110
  0x119D4,  # Mn Nandinagari - w4 100011000110
  0x119E0,  # Mn Nandinagari - w4 000001000110
  0x119E2,  # Po Nandinagari - w4 000000100110
  0x11A00,  # Lo Zanabazar_Square - w4 100011000110
  0x11A01,  # Mn Zanabazar_Square - w4 100011000110
  0x11A33,  # Mn Zanabazar_Square - w4 000001000110
  0x11A39,  # Mc Zanabazar_Square - w4 100011000110
  0x11A3F,  # Po Zanabazar_Square - w4 000000100110
  0x11A50,  # Lo Soyombo - w4 100011000110
  0x11A51,  # Mn Soyombo - w4 100011000110
  0x11A57,  # Mc Soyombo - w4 100011000110
  0x11A98,  # Mn Soyombo - w4 000001000110
  0x11A9A,  # Po Soyombo - w4 000000100110
  0x11AB0,  # Lo Canadian_Aboriginal - w4 100011000110
  0x11AC0,  # Lo Pau_Cin_Hau - w4 100011000110
  0x11B00,  # Po Devanagari - w4 000000100110
  0x11BC0,  # Lo Sunuwar - w4 100011000110
  0x11BE1,  # Po Sunuwar - w4 000000100110
  0x11BF0,  # Nd Sunuwar - w4 000111000110
  0x11C00,  # Lo Bhaiksuki - w4 100011000110
  0x11C2F,  # Mc Bhaiksuki - w4 100011000110
  0x11C30,  # Mn Bhaiksuki - w4 100011000110
  0x11C3F,  # Mn Bhaiksuki - w4 000001000110
  0x11C41,  # Po Bhaiksuki - w4 000000100110
  0x11C50,  # Nd Bhaiksuki - w4 000111000110
  0x11C5A,  # No Bhaiksuki - w4 000000000110
  0x11C70,  # Po Marchen - w4 000000100110
  0x11C72,  # Lo Marchen - w4 100011000110
  0x11C92,  # Mn Marchen - w4 100011000110
  0x11CA9,  # Mc Marchen - w4 100011000110
  0x11D00,  # Lo Masaram_Gondi - w4 100011000110
  0x11D31,  # Mn Masaram_Gondi - w4 100011000110
  0x11D42,  # Mn Masaram_Gondi - w4 000001000110
  0x11D50,  # Nd Masaram_Gondi - w4 000111000110
  0x11D60,  # Lo Gunjala_Gondi - w4 100011000110
  0x11D8A,  # Mc Gunjala_Gondi - w4 100011000110
  0x11D90,  # Mn Gunjala_Gondi - w4 100011000110
  0x11D97,  # Mn Gunjala_Gondi - w4 000001000110
  0x11DA0,  # Nd Gunjala_Gondi - w4 000111000110
  0x11DB0,  # Lo Tolong_Siki - w4 100011000110
  0x11DD9,  # Lm Tolong_Siki - w4 100011000110
  0x11DE0,  # Nd Tolong_Siki - w4 000111000110
  0x11EE0,  # Lo Makasar - w4 100011000110
  0x11EF3,  # Mn Makasar - w4 100011000110
  0x11EF5,  # Mc Makasar - w4 100011000110
  0x11EF7,  # Po Makasar - w4 000000100110
  0x11F00,  # Mn Kawi - w4 100011000110
  0x11F02,  # Lo Kawi - w4 100011000110
  0x11F03,  # Mc Kawi - w4 100011000110
  0x11F41,  # Mc Kawi - w4 000001000110
  0x11F42,  # Mn Kawi - w4 000001000110
  0x11F43,  # Po Kawi - w4 000000100110
  0x11F50,  # Nd Kawi - w4 000111000110
  0x11FB0,  # Lo Lisu - w4 100011000110
  0x11FC0,  # No Tamil - w4 000000000110
  0x11FD5,  # So Tamil - w4 000000000110
  0x11FDD,  # Sc Tamil - w4 000000000110
  0x11FFF,  # Po Tamil - w4 000000100110
  0x12000,  # Lo Cuneiform - w4 100011000110
  0x12400,  # Nl Cuneiform - w4 100011000110
  0x12470,  # Po Cuneiform - w4 000000100110
  0x12F90,  # Lo Cypro_Minoan - w4 100011000110
  0x12FF1,  # Po Cypro_Minoan - w4 000000100110
  0x13000,  # Lo Egyptian_Hieroglyphs - w4 100011000110
  0x13430,  # Cf Egyptian_Hieroglyphs - w4 000000000110
  0x13440,  # Mn Egyptian_Hieroglyphs - w4 000001000110
  0x14400,  # Lo Anatolian_Hieroglyphs - w4 100011000110
  0x16100,  # Lo Gurung_Khema - w4 100011000110
  0x1611E,  # Mn Gurung_Khema - w4 100011000110
  0x1612A,  # Mc Gurung_Khema - w4 100011000110
  0x1612F,  # Mn Gurung_Khema - w4 000001000110
  0x16130,  # Nd Gurung_Khema - w4 000111000110
  0x16800,  # Lo Bamum - w4 100011000110
  0x16A40,  # Lo Mro - w4 100011000110
  0x16A60,  # Nd Mro - w4 000111000110
  0x16A6E,  # Po Mro - w4 000000100110
  0x16A70,  # Lo Tangsa - w4 100011000110
  0x16AC0,  # Nd Tangsa - w4 000111000110
  0x16AD0,  # Lo Bassa_Vah - w4 100011000110
  0x16AF0,  # Mn Bassa_Vah - w4 000001000110
  0x16AF5,  # Po Bassa_Vah - w4 000000100110
  0x16B00,  # Lo Pahawh_Hmong - w4 100011000110
  0x16B30,  # Mn Pahawh_Hmong - w4 000001000110
  0x16B37,  # Po Pahawh_Hmong - w4 000000100110
  0x16B3C,  # So Pahawh_Hmong - w4 000000000110
  0x16B40,  # Lm Pahawh_Hmong - w4 100011000110
  0x16B50,  # Nd Pahawh_Hmong - w4 000111000110
  0x16B5B,  # No Pahawh_Hmong - w4 000000000110
  0x16D40,  # Lm Kirat_Rai - w4 100011000110
  0x16D43,  # Lo Kirat_Rai - w4 100011000110
  0x16D6D,  # Po Kirat_Rai - w4 000000100110
  0x16D70,  # Nd Kirat_Rai - w4 000111000110
  0x16E40,  # Lu Medefaidrin C w4 110011000110
  0x16E60,  # Ll Medefaidrin - w4 101011000110
  0x16E80,  # No Medefaidrin - w4 000000000110
  0x16E97,  # Po Medefaidrin - w4 000000100110
  0x16EA0,  # Lu Beria_Erfe C w4 110011000110
  0x16EBB,  # Ll Beria_Erfe - w4 101011000110
  0x16F00,  # Lo Miao - w4 100011000110
  0x16F4F,  # Mn Miao - w4 100011000110
  0x16F51,  # Mc Miao - w4 100011000110
  0x16F93,  # Lm Miao - w4 100011000110
  0x16FE0,  # Lm Tangut - w4 100011000110
  0x16FE1,  # Lm Nushu - w4 100011000110
  0x16FE2,  # Po Han - w4 000000100110
  0x16FE3,  # Lm Han - w4 100011000110
  0x16FE4,  # Mn Khitan_Small_Script - w4 000001000110
  0x16FF0,  # Mc Han - w4 100011000110
  0x16FF4,  # Nl Han - w4 100011000110
  0x17000,  # Lo Tangut - w4 100011000110
  0x18B00,  # Lo Khitan_Small_Script - w4 100011000110
  0x1AFF0,  # Lm Katakana - w4 100011000110
  0x1B000,  # Lo Katakana - w4 100011000110
  0x1B001,  # Lo Hiragana - w4 100011000110
  0x1B170,  # Lo Nushu - w4 100011000110
  0x1BC00,  # Lo Duployan - w4 100011000110
  0x1BC9C,  # So Duployan - w4 000000000110
  0x1BC9D,  # Mn Duployan - w4 000001000110
  0x1BC9E,  # Mn Duployan - w4 100011000110
  0x1BC9F,  # Po Duployan - w4 000000100110
  0x1BCA0,  # Cf Common - w4 000000000110
  0x1CCF0,  # Nd Common - w4 000111000110
  0x1CEF0,  # Sm Common - w4 000000000110
  0x1D165,  # Mc Common - w4 000001000110
  0x1D242,  # Mn Greek - w4 000001000110
  0x1D400,  # Lu Common - w4 110011000110
  0x1D41A,  # Ll Common - w4 101011000110
  0x1D800,  # So SignWriting - w4 000000000110
  0x1DA00,  # Mn SignWriting - w4 000001000110
  0x1DA87,  # Po SignWriting - w4 000000100110
  0x1DF00,  # Ll Latin - w4 101011000110
  0x1DF0A,  # Lo Latin - w4 100011000110
  0x1E000,  # Mn Glagolitic - w4 100011000110
  0x1E030,  # Lm Cyrillic - w4 101011000110
  0x1E08F,  # Mn Cyrillic - w4 100011000110
  0x1E100,  # Lo Nyiakeng_Puachue_Hmong - w4 100011000110
  0x1E130,  # Mn Nyiakeng_Puachue_Hmong - w4 000001000110
  0x1E137,  # Lm Nyiakeng_Puachue_Hmong - w4 100011000110
  0x1E140,  # Nd Nyiakeng_Puachue_Hmong - w4 000111000110
  0x1E14F,  # So Nyiakeng_Puachue_Hmong - w4 000000000110
  0x1E290,  # Lo Toto - w4 100011000110
  0x1E2AE,  # Mn Toto - w4 000001000110
  0x1E2C0,  # Lo Wancho - w4 100011000110
  0x1E2EC,  # Mn Wancho - w4 000001000110
  0x1E2F0,  # Nd Wancho - w4 000111000110
  0x1E2FF,  # Sc Wancho - w4 000000000110
  0x1E4D0,  # Lo Nag_Mundari - w4 100011000110
  0x1E4EB,  # Lm Nag_Mundari - w4 100011000110
  0x1E4EC,  # Mn Nag_Mundari - w4 000001000110
  0x1E4F0,  # Nd Nag_Mundari - w4 000111000110
  0x1E5D0,  # Lo Ol_Onal - w4 100011000110
  0x1E5EE,  # Mn Ol_Onal - w4 000001000110
  0x1E5F1,  # Nd Ol_Onal - w4 000111000110
  0x1E5FF,  # Po Ol_Onal - w4 000000100110
  0x1E6C0,  # Lo Tai_Yo - w4 100011000110
  0x1E6E3,  # Mn Tai_Yo - w4 100011000110
  0x1E6FF,  # Lm Tai_Yo - w4 100011000110
  0x1E7E0,  # Lo Ethiopic - w4 100011000110
  0x1E800,  # Lo Mende_Kikakui - w4 100011000110
  0x1E8C7,  # No Mende_Kikakui - w4 000000000110
  0x1E8D0,  # Mn Mende_Kikakui - w4 000001000110
  0x1E900,  # Lu Adlam C w4 110011000110
  0x1E922,  # Ll Adlam - w4 101011000110
  0x1E944,  # Mn Adlam - w4 000001000110
  0x1E947,  # Mn Adlam - w4 100011000110
  0x1E94B,  # Lm Adlam - w4 100011000110
  0x1E950,  # Nd Adlam - w4 000111000110
  0x1E95E,  # Po Adlam - w4 000000100110
  0x1ECB0,  # Sc Common - w4 000000000110
  0x1EEF0,  # Sm Arabic - w4 000000000110
  0x1F130,  # So Common - w4 110011000110
  0x1F200,  # So Hiragana - w4 000000000110
  0x1F3FB,  # Sk Common - w4 000000000110
  0x1FFFE,  # Cn Unknown - w4 000000000000
  0x20000,  # Lo Han - w4 100011000110
  0xF0000,  # Co Unknown - w4 000000000110
  0x10FFFD,  # boundary
  0x10FFFF,  # boundary
]

# 995 characters.
