# Generate the characters the differential test asks about, from the Unicode
# Character Database.
#
#   ruby mrbgems/mruby-regexp/tools/difftest/gen_corpus.rb OUTDIR [UCDDIR]
#
# UCDDIR holds the files ucd.rb names and defaults to the copy it points at.
# Which characters are chosen, and why those, is tools/unicode/corpus_data.rb's
# to say; this file only writes the answer out.
#
# corpus.rb is Ruby that runs under CRuby and under mruby, since compare.rb
# puts it in front of probe.rb and hands the pair to each engine. It is
# committed, like the tables are, so that the two engines are asked about the
# same characters whether or not the database is on the machine.

require_relative '../../../../tools/unicode/corpus_data'

outdir = ARGV[0] or abort "usage: #{$0} OUTDIR [UCDDIR]"
data = Unicode::CorpusData.load(ARGV[1])

File.open(File.join(outdir, 'corpus.rb'), 'w') do |out|
  out.puts <<~HEAD
    # The characters the differential test asks about.
    #
    # Generated by mrbgems/mruby-regexp/tools/difftest/gen_corpus.rb from the
    # Unicode #{data.version} character database. Do not edit by hand.
    #
    # One character out of every class the engine's tables tell apart, where a
    # class is a whole signature and not one property at a time: the general
    # category, the script, which POSIX types hold the character, the shape its
    # case folding takes and the width the encoding spells it in. Each is the
    # lowest codepoint of its signature no newer than Unicode #{Unicode::CorpusData::MAX_AGE},
    # which is the release the CRuby the corpus is compared against carries, so
    # that a character the two databases disagree about cannot be read as an
    # engine that does. The whole of ASCII is taken as well, being what almost
    # every pattern is written against.
    #
    # The comment beside each is its signature, spelled as
    #
    #   <general category> <script> <folding> w<width> <POSIX types>
    #
    # with the folding `C` a folding to one other character, `F` one that
    # expands into several and `-` none, and one bit per POSIX type in this
    # order:
    #
    #   #{Unicode::CorpusData::TYPE_NAMES.join(' ')}
    #
    # A codepoint taken for something other than its signature says so instead.
    #
    # See Copyright Notice in mruby.h

    CORPUS = [
  HEAD
  data.codepoints.each do |cp, why|
    out.puts "  0x%04X,  # %s" % [cp, why]
  end
  out.puts "]"
  out.puts
  out.puts "# #{data.codepoints.size} characters."
end

$stderr.puts "wrote #{File.join(outdir, 'corpus.rb')}: " \
             "#{data.codepoints.size} characters"
