/*
** This file is auto generated by mksymtbl.rb.
** DO NOT EDIT THIS FILE!
*/

/*
** STATISTICS
**  table size = 401 symbols * sizeof(symbol_name) = 3208 bytes (for 32 bit platform)
**  combined pool size = 2712 bytes (+ 342 NUL bytes)
**  uncombined pool size = 2906 bytes (+ 401 NUL bytes)
*/

static const char builtin_symbols_pool0[] =
  "!=\x00" "!~\x00" "$0\x00" "$DEBUG\x00" "%\x00" "&\x00" "**\x00" "+\x00"
  "+@\x00" "-\x00" "-@\x00" "/\x00" "<<\x00" "<=\x00" "<=>\x00" "===\x00"
  "=~\x00" ">=\x00" ">>\x00" "@args\x00" "@name\x00" "@result\x00"
  "ARGV\x00" "ArgumentError\x00" "Array\x00" "BasicObject\x00"
  "Comparable\x00" "Enumerable\x00" "Exception\x00" "FalseClass\x00"
  "Fixnum\x00" "Float\x00" "FloatDomainError\x00" "FrozenError\x00"
  "GC\x00" "Hash\x00" "INFINITY\x00" "IndexError\x00" "Integer\x00"
  "Integral\x00" "Kernel\x00" "KeyError\x00" "LocalJumpError\x00"
  "MRUBY_COPYRIGHT\x00" "MRUBY_DESCRIPTION\x00" "MRUBY_RELEASE_DATE\x00"
  "MRUBY_RELEASE_NO\x00" "MRUBY_VERSION\x00" "Module\x00" "NAN\x00"
  "NameError\x00" "NilClass\x00" "NoMemoryError\x00" "NoMethodError\x00"
  "NotImplementedError\x00" "Numeric\x00" "Proc\x00" "RUBY_ENGINE\x00"
  "RUBY_ENGINE_VERSION\x00" "Range\x00" "RangeError\x00" "Regexp\x00"
  "RegexpError\x00" "RuntimeError\x00" "ScriptError\x00"
  "StandardError\x00" "StopIteration\x00" "String\x00" "Symbol\x00"
  "SyntaxError\x00" "SystemStackError\x00" "TrueClass\x00" "TypeError\x00"
  "[]\x00" "[]=\x00" "^\x00" "__ary_cmp\x00" "__ary_eq\x00"
  "__ary_index\x00" "__attached__\x00" "__case_eqq\x00" "__classname__\x00"
  "__delete\x00" "__id__\x00" "__outer__\x00" "__printstr__\x00"
  "__send__\x00" "__sort_sub__\x00" "__sub_replace\x00" "__svalue\x00"
  "__update\x00" "__update_hash\x00" "_gc_root_\x00" "_inspect\x00" "`\x00"
  "abs\x00" "alias_method\x00" "all?\x00" "all_symbols\x00" "ancestors\x00"
  "anum\x00" "any?\x00" "append\x00" "append_features\x00" "arity\x00"
  "ary_F\x00" "ary_T\x00" "attr\x00" "attr_accessor\x00" "attr_reader\x00"
  "attr_writer\x00" "begin\x00" "between?\x00" "block\x00"
  "block_given?\x00" "bytes\x00" "bytesize\x00" "call\x00" "capitalize\x00"
  "capitalize!\x00" "casecmp\x00" "casecmp?\x00" "ceil\x00" "chomp\x00"
  "chomp!\x00" "chop\x00" "chop!\x00" "class_defined?\x00" "class_eval\x00"
  "class_variable_defined?\x00" "class_variable_get\x00"
  "class_variable_set\x00" "class_variables\x00" "clear\x00" "clone\x00"
  "collect\x00" "collect!\x00" "concat\x00" "const_defined?\x00"
  "const_get\x00" "const_missing\x00" "const_set\x00" "constants\x00"
  "default\x00" "default=\x00" "default_proc\x00" "default_proc=\x00"
  "define_method\x00" "define_singleton_method\x00" "delete_at\x00"
  "detect\x00" "disable\x00" "divmod\x00" "downcase\x00" "downcase!\x00"
  "downto\x00" "dup\x00" "each_byte\x00" "each_char\x00" "each_index\x00"
  "each_key\x00" "each_line\x00" "each_value\x00" "each_with_index\x00"
  "empty?\x00" "enable\x00" "entries\x00" "eql?\x00" "equal?\x00"
  "exception\x00" "exclude_end?\x00" "extend\x00" "extend_object\x00"
  "extended\x00" "file\x00" "find\x00" "find_all\x00" "first\x00"
  "flag\x00" "floor\x00" "format\x00" "found\x00" "freeze\x00"
  "frozen?\x00" "generational_mode\x00" "generational_mode=\x00"
  "global_variables\x00" "grep\x00" "gsub\x00" "gsub!\x00" "has_key?\x00"
  "has_value?\x00" "head\x00" "id2name\x00" "idx\x00" "ifnone\x00"
  "include\x00" "include?\x00" "included\x00" "included_modules\x00"
  "infinite?\x00" "inherited\x00" "initialize\x00" "initialize_copy\x00"
  "inject\x00" "instance_eval\x00" "instance_methods\x00"
  "instance_of?\x00" "instance_variable_defined?\x00"
  "instance_variable_get\x00" "instance_variable_set\x00"
  "instance_variables\x00" "intern\x00" "interval_ratio\x00"
  "interval_ratio=\x00" "is_a?\x00" "iterator?\x00" "join\x00" "keys\x00"
  "kind_of?\x00" "lambda\x00" "last\x00" "left\x00" "length\x00" "lhs\x00"
  "lim\x00" "local_variables\x00" "loop\x00" "map\x00" "map!\x00"
  "match\x00" "max\x00" "member?\x00" "merge\x00" "mesg\x00" "message\x00"
  "method_defined?\x00" "method_missing\x00" "method_removed\x00" "min\x00"
  "module_eval\x00" "module_function\x00" "name=\x00" "names\x00"
  "nan?\x00" "nesting\x00" "new\x00" "next\x00" "nil?\x00" "obj\x00"
  "object_id\x00" "offset\x00" "other\x00" "partition\x00" "pattern\x00"
  "pivot\x00" "plen\x00" "pop\x00" "pos\x00" "posnum\x00" "post\x00"
  "pre\x00" "prepend\x00" "prepend_features\x00" "prepended\x00"
  "print\x00" "private\x00" "private_methods\x00" "protected\x00"
  "protected_methods\x00" "public\x00" "public_methods\x00" "push\x00"
  "puts\x00" "quo\x00" "raise\x00" "reduce\x00" "reg\x00" "rehash\x00"
  "reject\x00" "reject!\x00" "remove_class_variable\x00" "remove_const\x00"
  "remove_instance_variable\x00" "remove_method\x00" "respond_to?\x00"
  "respond_to_missing?\x00" "result=\x00" "ret\x00" "reverse\x00"
  "reverse!\x00" "rhs\x00" "right\x00" "rindex\x00" "round\x00"
  "rs_len\x00" "scan\x00" "select\x00" "select!\x00" "send\x00"
  "set_backtrace\x00" "singleton_class\x00" "singleton_methods\x00"
  "slice\x00" "sort\x00" "sort!\x00" "split\x00" "sprintf\x00" "stack\x00"
  "start\x00" "step\x00" "step_ratio\x00" "step_ratio=\x00" "store\x00"
  "str_each\x00" "succ\x00" "superclass\x00" "sv\x00" "tail\x00" "this\x00"
  "times\x00" "tmp\x00" "to_a\x00" "to_ary\x00" "to_enum\x00" "to_f\x00"
  "to_hash\x00" "to_i\x00" "to_int\x00" "to_proc\x00" "to_s\x00"
  "to_str\x00" "to_sym\x00" "truncate\x00" "undef_method\x00" "unshift\x00"
  "upcase\x00" "upcase!\x00" "upto\x00" "vals\x00" "values\x00" "|\x00";

static const symbol_name builtin_symbols_table[] = {
  { 1,  1, &builtin_symbols_pool0 [1054] }, /*   -1 "!" */
  { 1,  2, &builtin_symbols_pool0 [   0] }, /*   -2 "!=" */
  { 1,  2, &builtin_symbols_pool0 [   3] }, /*   -3 "!~" */
  { 1,  2, &builtin_symbols_pool0 [   6] }, /*   -4 "$0" */
  { 1,  6, &builtin_symbols_pool0 [   9] }, /*   -5 "$DEBUG" */
  { 1,  1, &builtin_symbols_pool0 [  16] }, /*   -6 "%" */
  { 1,  1, &builtin_symbols_pool0 [  18] }, /*   -7 "&" */
  { 1,  1, &builtin_symbols_pool0 [  21] }, /*   -8 "*" */
  { 1,  2, &builtin_symbols_pool0 [  20] }, /*   -9 "**" */
  { 1,  1, &builtin_symbols_pool0 [  23] }, /*  -10 "+" */
  { 1,  2, &builtin_symbols_pool0 [  25] }, /*  -11 "+@" */
  { 1,  1, &builtin_symbols_pool0 [  28] }, /*  -12 "-" */
  { 1,  2, &builtin_symbols_pool0 [  30] }, /*  -13 "-@" */
  { 1,  1, &builtin_symbols_pool0 [  33] }, /*  -14 "/" */
  { 1,  1, &builtin_symbols_pool0 [  36] }, /*  -15 "<" */
  { 1,  2, &builtin_symbols_pool0 [  35] }, /*  -16 "<<" */
  { 1,  2, &builtin_symbols_pool0 [  38] }, /*  -17 "<=" */
  { 1,  3, &builtin_symbols_pool0 [  41] }, /*  -18 "<=>" */
  { 1,  2, &builtin_symbols_pool0 [  46] }, /*  -19 "==" */
  { 1,  3, &builtin_symbols_pool0 [  45] }, /*  -20 "===" */
  { 1,  2, &builtin_symbols_pool0 [  49] }, /*  -21 "=~" */
  { 1,  1, &builtin_symbols_pool0 [  43] }, /*  -22 ">" */
  { 1,  2, &builtin_symbols_pool0 [  52] }, /*  -23 ">=" */
  { 1,  2, &builtin_symbols_pool0 [  55] }, /*  -24 ">>" */
  { 1,  5, &builtin_symbols_pool0 [  58] }, /*  -25 "@args" */
  { 1,  5, &builtin_symbols_pool0 [  64] }, /*  -26 "@name" */
  { 1,  7, &builtin_symbols_pool0 [  70] }, /*  -27 "@result" */
  { 1,  4, &builtin_symbols_pool0 [  78] }, /*  -28 "ARGV" */
  { 1, 13, &builtin_symbols_pool0 [  83] }, /*  -29 "ArgumentError" */
  { 1,  5, &builtin_symbols_pool0 [  97] }, /*  -30 "Array" */
  { 1, 11, &builtin_symbols_pool0 [ 103] }, /*  -31 "BasicObject" */
  { 1,  5, &builtin_symbols_pool0 [ 152] }, /*  -32 "Class" */
  { 1, 10, &builtin_symbols_pool0 [ 115] }, /*  -33 "Comparable" */
  { 1, 10, &builtin_symbols_pool0 [ 126] }, /*  -34 "Enumerable" */
  { 1,  9, &builtin_symbols_pool0 [ 137] }, /*  -35 "Exception" */
  { 1, 10, &builtin_symbols_pool0 [ 147] }, /*  -36 "FalseClass" */
  { 1,  6, &builtin_symbols_pool0 [ 158] }, /*  -37 "Fixnum" */
  { 1,  5, &builtin_symbols_pool0 [ 165] }, /*  -38 "Float" */
  { 1, 16, &builtin_symbols_pool0 [ 171] }, /*  -39 "FloatDomainError" */
  { 1, 11, &builtin_symbols_pool0 [ 188] }, /*  -40 "FrozenError" */
  { 1,  2, &builtin_symbols_pool0 [ 200] }, /*  -41 "GC" */
  { 1,  4, &builtin_symbols_pool0 [ 203] }, /*  -42 "Hash" */
  { 1,  8, &builtin_symbols_pool0 [ 208] }, /*  -43 "INFINITY" */
  { 1, 10, &builtin_symbols_pool0 [ 217] }, /*  -44 "IndexError" */
  { 1,  7, &builtin_symbols_pool0 [ 228] }, /*  -45 "Integer" */
  { 1,  8, &builtin_symbols_pool0 [ 236] }, /*  -46 "Integral" */
  { 1,  6, &builtin_symbols_pool0 [ 245] }, /*  -47 "Kernel" */
  { 1,  8, &builtin_symbols_pool0 [ 252] }, /*  -48 "KeyError" */
  { 1, 14, &builtin_symbols_pool0 [ 261] }, /*  -49 "LocalJumpError" */
  { 1, 15, &builtin_symbols_pool0 [ 276] }, /*  -50 "MRUBY_COPYRIGHT" */
  { 1, 17, &builtin_symbols_pool0 [ 292] }, /*  -51 "MRUBY_DESCRIPTION" */
  { 1, 18, &builtin_symbols_pool0 [ 310] }, /*  -52 "MRUBY_RELEASE_DATE" */
  { 1, 16, &builtin_symbols_pool0 [ 329] }, /*  -53 "MRUBY_RELEASE_NO" */
  { 1, 13, &builtin_symbols_pool0 [ 346] }, /*  -54 "MRUBY_VERSION" */
  { 1,  6, &builtin_symbols_pool0 [ 360] }, /*  -55 "Module" */
  { 1,  3, &builtin_symbols_pool0 [ 367] }, /*  -56 "NAN" */
  { 1,  9, &builtin_symbols_pool0 [ 371] }, /*  -57 "NameError" */
  { 1,  8, &builtin_symbols_pool0 [ 381] }, /*  -58 "NilClass" */
  { 1, 13, &builtin_symbols_pool0 [ 390] }, /*  -59 "NoMemoryError" */
  { 1, 13, &builtin_symbols_pool0 [ 404] }, /*  -60 "NoMethodError" */
  { 1, 19, &builtin_symbols_pool0 [ 418] }, /*  -61 "NotImplementedError" */
  { 1,  7, &builtin_symbols_pool0 [ 438] }, /*  -62 "Numeric" */
  { 1,  6, &builtin_symbols_pool0 [ 108] }, /*  -63 "Object" */
  { 1,  4, &builtin_symbols_pool0 [ 446] }, /*  -64 "Proc" */
  { 1, 11, &builtin_symbols_pool0 [ 451] }, /*  -65 "RUBY_ENGINE" */
  { 1, 19, &builtin_symbols_pool0 [ 463] }, /*  -66 "RUBY_ENGINE_VERSION" */
  { 1, 12, &builtin_symbols_pool0 [ 347] }, /*  -67 "RUBY_VERSION" */
  { 1,  5, &builtin_symbols_pool0 [ 483] }, /*  -68 "Range" */
  { 1, 10, &builtin_symbols_pool0 [ 489] }, /*  -69 "RangeError" */
  { 1,  6, &builtin_symbols_pool0 [ 500] }, /*  -70 "Regexp" */
  { 1, 11, &builtin_symbols_pool0 [ 507] }, /*  -71 "RegexpError" */
  { 1, 12, &builtin_symbols_pool0 [ 519] }, /*  -72 "RuntimeError" */
  { 1, 11, &builtin_symbols_pool0 [ 532] }, /*  -73 "ScriptError" */
  { 1, 13, &builtin_symbols_pool0 [ 544] }, /*  -74 "StandardError" */
  { 1, 13, &builtin_symbols_pool0 [ 558] }, /*  -75 "StopIteration" */
  { 1,  6, &builtin_symbols_pool0 [ 572] }, /*  -76 "String" */
  { 1,  6, &builtin_symbols_pool0 [ 579] }, /*  -77 "Symbol" */
  { 1, 11, &builtin_symbols_pool0 [ 586] }, /*  -78 "SyntaxError" */
  { 1, 16, &builtin_symbols_pool0 [ 598] }, /*  -79 "SystemStackError" */
  { 1,  9, &builtin_symbols_pool0 [ 615] }, /*  -80 "TrueClass" */
  { 1,  9, &builtin_symbols_pool0 [ 625] }, /*  -81 "TypeError" */
  { 1,  2, &builtin_symbols_pool0 [ 635] }, /*  -82 "[]" */
  { 1,  3, &builtin_symbols_pool0 [ 638] }, /*  -83 "[]=" */
  { 1,  1, &builtin_symbols_pool0 [ 642] }, /*  -84 "^" */
  { 1,  9, &builtin_symbols_pool0 [ 644] }, /*  -85 "__ary_cmp" */
  { 1,  8, &builtin_symbols_pool0 [ 654] }, /*  -86 "__ary_eq" */
  { 1, 11, &builtin_symbols_pool0 [ 663] }, /*  -87 "__ary_index" */
  { 1, 12, &builtin_symbols_pool0 [ 675] }, /*  -88 "__attached__" */
  { 1, 10, &builtin_symbols_pool0 [ 688] }, /*  -89 "__case_eqq" */
  { 1, 13, &builtin_symbols_pool0 [ 699] }, /*  -90 "__classname__" */
  { 1,  8, &builtin_symbols_pool0 [ 713] }, /*  -91 "__delete" */
  { 1,  6, &builtin_symbols_pool0 [ 722] }, /*  -92 "__id__" */
  { 1,  9, &builtin_symbols_pool0 [ 729] }, /*  -93 "__outer__" */
  { 1, 12, &builtin_symbols_pool0 [ 739] }, /*  -94 "__printstr__" */
  { 1,  8, &builtin_symbols_pool0 [ 752] }, /*  -95 "__send__" */
  { 1, 12, &builtin_symbols_pool0 [ 761] }, /*  -96 "__sort_sub__" */
  { 1, 13, &builtin_symbols_pool0 [ 774] }, /*  -97 "__sub_replace" */
  { 1,  8, &builtin_symbols_pool0 [ 788] }, /*  -98 "__svalue" */
  { 1,  8, &builtin_symbols_pool0 [ 797] }, /*  -99 "__update" */
  { 1, 13, &builtin_symbols_pool0 [ 806] }, /* -100 "__update_hash" */
  { 1,  9, &builtin_symbols_pool0 [ 820] }, /* -101 "_gc_root_" */
  { 1,  8, &builtin_symbols_pool0 [ 830] }, /* -102 "_inspect" */
  { 1,  1, &builtin_symbols_pool0 [ 839] }, /* -103 "`" */
  { 1,  1, &builtin_symbols_pool0 [2096] }, /* -104 "a" */
  { 1,  3, &builtin_symbols_pool0 [ 841] }, /* -105 "abs" */
  { 1, 12, &builtin_symbols_pool0 [ 845] }, /* -106 "alias_method" */
  { 1,  4, &builtin_symbols_pool0 [ 858] }, /* -107 "all?" */
  { 1, 11, &builtin_symbols_pool0 [ 863] }, /* -108 "all_symbols" */
  { 1,  9, &builtin_symbols_pool0 [ 875] }, /* -109 "ancestors" */
  { 1,  4, &builtin_symbols_pool0 [ 885] }, /* -110 "anum" */
  { 1,  4, &builtin_symbols_pool0 [ 890] }, /* -111 "any?" */
  { 1,  6, &builtin_symbols_pool0 [ 895] }, /* -112 "append" */
  { 1, 15, &builtin_symbols_pool0 [ 902] }, /* -113 "append_features" */
  { 1,  4, &builtin_symbols_pool0 [  59] }, /* -114 "args" */
  { 1,  5, &builtin_symbols_pool0 [ 918] }, /* -115 "arity" */
  { 1,  3, &builtin_symbols_pool0 [2926] }, /* -116 "ary" */
  { 1,  5, &builtin_symbols_pool0 [ 924] }, /* -117 "ary_F" */
  { 1,  5, &builtin_symbols_pool0 [ 930] }, /* -118 "ary_T" */
  { 1,  4, &builtin_symbols_pool0 [ 936] }, /* -119 "attr" */
  { 1, 13, &builtin_symbols_pool0 [ 941] }, /* -120 "attr_accessor" */
  { 1, 11, &builtin_symbols_pool0 [ 955] }, /* -121 "attr_reader" */
  { 1, 11, &builtin_symbols_pool0 [ 967] }, /* -122 "attr_writer" */
  { 1,  1, &builtin_symbols_pool0 [1735] }, /* -123 "b" */
  { 1,  9, &builtin_symbols_pool0 [2749] }, /* -124 "backtrace" */
  { 1,  5, &builtin_symbols_pool0 [ 979] }, /* -125 "begin" */
  { 1,  8, &builtin_symbols_pool0 [ 985] }, /* -126 "between?" */
  { 1,  5, &builtin_symbols_pool0 [ 994] }, /* -127 "block" */
  { 1, 12, &builtin_symbols_pool0 [1000] }, /* -128 "block_given?" */
  { 1,  5, &builtin_symbols_pool0 [1013] }, /* -129 "bytes" */
  { 1,  8, &builtin_symbols_pool0 [1019] }, /* -130 "bytesize" */
  { 1,  1, &builtin_symbols_pool0 [ 444] }, /* -131 "c" */
  { 1,  4, &builtin_symbols_pool0 [1028] }, /* -132 "call" */
  { 1, 10, &builtin_symbols_pool0 [1033] }, /* -133 "capitalize" */
  { 1, 11, &builtin_symbols_pool0 [1044] }, /* -134 "capitalize!" */
  { 1,  7, &builtin_symbols_pool0 [1056] }, /* -135 "casecmp" */
  { 1,  8, &builtin_symbols_pool0 [1064] }, /* -136 "casecmp?" */
  { 1,  4, &builtin_symbols_pool0 [1073] }, /* -137 "ceil" */
  { 1,  5, &builtin_symbols_pool0 [1078] }, /* -138 "chomp" */
  { 1,  6, &builtin_symbols_pool0 [1084] }, /* -139 "chomp!" */
  { 1,  4, &builtin_symbols_pool0 [1091] }, /* -140 "chop" */
  { 1,  5, &builtin_symbols_pool0 [1096] }, /* -141 "chop!" */
  { 1,  5, &builtin_symbols_pool0 [2769] }, /* -142 "class" */
  { 1, 14, &builtin_symbols_pool0 [1102] }, /* -143 "class_defined?" */
  { 1, 10, &builtin_symbols_pool0 [1117] }, /* -144 "class_eval" */
  { 1, 23, &builtin_symbols_pool0 [1128] }, /* -145 "class_variable_defined?" */
  { 1, 18, &builtin_symbols_pool0 [1152] }, /* -146 "class_variable_get" */
  { 1, 18, &builtin_symbols_pool0 [1171] }, /* -147 "class_variable_set" */
  { 1, 15, &builtin_symbols_pool0 [1190] }, /* -148 "class_variables" */
  { 1,  5, &builtin_symbols_pool0 [1206] }, /* -149 "clear" */
  { 1,  5, &builtin_symbols_pool0 [1212] }, /* -150 "clone" */
  { 1,  3, &builtin_symbols_pool0 [ 650] }, /* -151 "cmp" */
  { 1,  7, &builtin_symbols_pool0 [1218] }, /* -152 "collect" */
  { 1,  8, &builtin_symbols_pool0 [1226] }, /* -153 "collect!" */
  { 1,  6, &builtin_symbols_pool0 [1235] }, /* -154 "concat" */
  { 1, 14, &builtin_symbols_pool0 [1242] }, /* -155 "const_defined?" */
  { 1,  9, &builtin_symbols_pool0 [1257] }, /* -156 "const_get" */
  { 1, 13, &builtin_symbols_pool0 [1267] }, /* -157 "const_missing" */
  { 1,  9, &builtin_symbols_pool0 [1281] }, /* -158 "const_set" */
  { 1,  9, &builtin_symbols_pool0 [1291] }, /* -159 "constants" */
  { 1,  7, &builtin_symbols_pool0 [1301] }, /* -160 "default" */
  { 1,  8, &builtin_symbols_pool0 [1309] }, /* -161 "default=" */
  { 1, 12, &builtin_symbols_pool0 [1318] }, /* -162 "default_proc" */
  { 1, 13, &builtin_symbols_pool0 [1331] }, /* -163 "default_proc=" */
  { 1, 13, &builtin_symbols_pool0 [1345] }, /* -164 "define_method" */
  { 1, 23, &builtin_symbols_pool0 [1359] }, /* -165 "define_singleton_method" */
  { 1,  6, &builtin_symbols_pool0 [ 715] }, /* -166 "delete" */
  { 1,  9, &builtin_symbols_pool0 [1383] }, /* -167 "delete_at" */
  { 1,  6, &builtin_symbols_pool0 [1393] }, /* -168 "detect" */
  { 1,  7, &builtin_symbols_pool0 [1400] }, /* -169 "disable" */
  { 1,  6, &builtin_symbols_pool0 [1408] }, /* -170 "divmod" */
  { 1,  8, &builtin_symbols_pool0 [1415] }, /* -171 "downcase" */
  { 1,  9, &builtin_symbols_pool0 [1424] }, /* -172 "downcase!" */
  { 1,  6, &builtin_symbols_pool0 [1434] }, /* -173 "downto" */
  { 1,  3, &builtin_symbols_pool0 [1441] }, /* -174 "dup" */
  { 1,  1, &builtin_symbols_pool0 [  68] }, /* -175 "e" */
  { 1,  4, &builtin_symbols_pool0 [2874] }, /* -176 "each" */
  { 1,  9, &builtin_symbols_pool0 [1445] }, /* -177 "each_byte" */
  { 1,  9, &builtin_symbols_pool0 [1455] }, /* -178 "each_char" */
  { 1, 10, &builtin_symbols_pool0 [1465] }, /* -179 "each_index" */
  { 1,  8, &builtin_symbols_pool0 [1476] }, /* -180 "each_key" */
  { 1,  9, &builtin_symbols_pool0 [1485] }, /* -181 "each_line" */
  { 1, 10, &builtin_symbols_pool0 [1495] }, /* -182 "each_value" */
  { 1, 15, &builtin_symbols_pool0 [1506] }, /* -183 "each_with_index" */
  { 1,  6, &builtin_symbols_pool0 [1522] }, /* -184 "empty?" */
  { 1,  6, &builtin_symbols_pool0 [1529] }, /* -185 "enable" */
  { 1,  3, &builtin_symbols_pool0 [ 898] }, /* -186 "end" */
  { 1,  7, &builtin_symbols_pool0 [1536] }, /* -187 "entries" */
  { 1,  4, &builtin_symbols_pool0 [1544] }, /* -188 "eql?" */
  { 1,  6, &builtin_symbols_pool0 [1549] }, /* -189 "equal?" */
  { 1,  9, &builtin_symbols_pool0 [1556] }, /* -190 "exception" */
  { 1, 12, &builtin_symbols_pool0 [1566] }, /* -191 "exclude_end?" */
  { 1,  6, &builtin_symbols_pool0 [1579] }, /* -192 "extend" */
  { 1, 13, &builtin_symbols_pool0 [1586] }, /* -193 "extend_object" */
  { 1,  8, &builtin_symbols_pool0 [1600] }, /* -194 "extended" */
  { 1,  4, &builtin_symbols_pool0 [1609] }, /* -195 "file" */
  { 1,  4, &builtin_symbols_pool0 [1614] }, /* -196 "find" */
  { 1,  8, &builtin_symbols_pool0 [1619] }, /* -197 "find_all" */
  { 1,  7, &builtin_symbols_pool0 [1832] }, /* -198 "finite?" */
  { 1,  5, &builtin_symbols_pool0 [1628] }, /* -199 "first" */
  { 1,  4, &builtin_symbols_pool0 [1634] }, /* -200 "flag" */
  { 1,  5, &builtin_symbols_pool0 [1639] }, /* -201 "floor" */
  { 1,  6, &builtin_symbols_pool0 [1645] }, /* -202 "format" */
  { 1,  5, &builtin_symbols_pool0 [1652] }, /* -203 "found" */
  { 1,  6, &builtin_symbols_pool0 [1658] }, /* -204 "freeze" */
  { 1,  7, &builtin_symbols_pool0 [1665] }, /* -205 "frozen?" */
  { 1, 17, &builtin_symbols_pool0 [1673] }, /* -206 "generational_mode" */
  { 1, 18, &builtin_symbols_pool0 [1691] }, /* -207 "generational_mode=" */
  { 1, 16, &builtin_symbols_pool0 [1710] }, /* -208 "global_variables" */
  { 1,  4, &builtin_symbols_pool0 [1727] }, /* -209 "grep" */
  { 1,  4, &builtin_symbols_pool0 [1732] }, /* -210 "gsub" */
  { 1,  5, &builtin_symbols_pool0 [1737] }, /* -211 "gsub!" */
  { 1,  1, &builtin_symbols_pool0 [ 206] }, /* -212 "h" */
  { 1,  8, &builtin_symbols_pool0 [1743] }, /* -213 "has_key?" */
  { 1, 10, &builtin_symbols_pool0 [1752] }, /* -214 "has_value?" */
  { 1,  4, &builtin_symbols_pool0 [ 815] }, /* -215 "hash" */
  { 1,  4, &builtin_symbols_pool0 [1763] }, /* -216 "head" */
  { 1,  1, &builtin_symbols_pool0 [2954] }, /* -217 "i" */
  { 1,  7, &builtin_symbols_pool0 [1768] }, /* -218 "id2name" */
  { 1,  3, &builtin_symbols_pool0 [1776] }, /* -219 "idx" */
  { 1,  6, &builtin_symbols_pool0 [1780] }, /* -220 "ifnone" */
  { 1,  7, &builtin_symbols_pool0 [1787] }, /* -221 "include" */
  { 1,  8, &builtin_symbols_pool0 [1795] }, /* -222 "include?" */
  { 1,  8, &builtin_symbols_pool0 [1804] }, /* -223 "included" */
  { 1, 16, &builtin_symbols_pool0 [1813] }, /* -224 "included_modules" */
  { 1,  5, &builtin_symbols_pool0 [ 669] }, /* -225 "index" */
  { 1,  9, &builtin_symbols_pool0 [1830] }, /* -226 "infinite?" */
  { 1,  9, &builtin_symbols_pool0 [1840] }, /* -227 "inherited" */
  { 1, 10, &builtin_symbols_pool0 [1850] }, /* -228 "initialize" */
  { 1, 15, &builtin_symbols_pool0 [1861] }, /* -229 "initialize_copy" */
  { 1,  6, &builtin_symbols_pool0 [1877] }, /* -230 "inject" */
  { 1,  7, &builtin_symbols_pool0 [ 831] }, /* -231 "inspect" */
  { 1, 13, &builtin_symbols_pool0 [1884] }, /* -232 "instance_eval" */
  { 1, 16, &builtin_symbols_pool0 [1898] }, /* -233 "instance_methods" */
  { 1, 12, &builtin_symbols_pool0 [1915] }, /* -234 "instance_of?" */
  { 1, 26, &builtin_symbols_pool0 [1928] }, /* -235 "instance_variable_defined?" */
  { 1, 21, &builtin_symbols_pool0 [1955] }, /* -236 "instance_variable_get" */
  { 1, 21, &builtin_symbols_pool0 [1977] }, /* -237 "instance_variable_set" */
  { 1, 18, &builtin_symbols_pool0 [1999] }, /* -238 "instance_variables" */
  { 1,  6, &builtin_symbols_pool0 [2018] }, /* -239 "intern" */
  { 1, 14, &builtin_symbols_pool0 [2025] }, /* -240 "interval_ratio" */
  { 1, 15, &builtin_symbols_pool0 [2040] }, /* -241 "interval_ratio=" */
  { 1,  5, &builtin_symbols_pool0 [2056] }, /* -242 "is_a?" */
  { 1,  9, &builtin_symbols_pool0 [2062] }, /* -243 "iterator?" */
  { 1,  1, &builtin_symbols_pool0 [2309] }, /* -244 "j" */
  { 1,  4, &builtin_symbols_pool0 [2072] }, /* -245 "join" */
  { 1,  1, &builtin_symbols_pool0 [ 998] }, /* -246 "k" */
  { 1,  3, &builtin_symbols_pool0 [1481] }, /* -247 "key" */
  { 1,  4, &builtin_symbols_pool0 [1747] }, /* -248 "key?" */
  { 1,  4, &builtin_symbols_pool0 [2077] }, /* -249 "keys" */
  { 1,  8, &builtin_symbols_pool0 [2082] }, /* -250 "kind_of?" */
  { 1,  6, &builtin_symbols_pool0 [2091] }, /* -251 "lambda" */
  { 1,  4, &builtin_symbols_pool0 [2098] }, /* -252 "last" */
  { 1,  4, &builtin_symbols_pool0 [2103] }, /* -253 "left" */
  { 1,  3, &builtin_symbols_pool0 [2359] }, /* -254 "len" */
  { 1,  6, &builtin_symbols_pool0 [2108] }, /* -255 "length" */
  { 1,  3, &builtin_symbols_pool0 [2115] }, /* -256 "lhs" */
  { 1,  3, &builtin_symbols_pool0 [2119] }, /* -257 "lim" */
  { 1,  4, &builtin_symbols_pool0 [1490] }, /* -258 "line" */
  { 1, 15, &builtin_symbols_pool0 [2123] }, /* -259 "local_variables" */
  { 1,  4, &builtin_symbols_pool0 [2139] }, /* -260 "loop" */
  { 1,  1, &builtin_symbols_pool0 [ 163] }, /* -261 "m" */
  { 1,  3, &builtin_symbols_pool0 [2144] }, /* -262 "map" */
  { 1,  4, &builtin_symbols_pool0 [2148] }, /* -263 "map!" */
  { 1,  5, &builtin_symbols_pool0 [2153] }, /* -264 "match" */
  { 1,  3, &builtin_symbols_pool0 [2159] }, /* -265 "max" */
  { 1,  7, &builtin_symbols_pool0 [2163] }, /* -266 "member?" */
  { 1,  5, &builtin_symbols_pool0 [2171] }, /* -267 "merge" */
  { 1,  4, &builtin_symbols_pool0 [2177] }, /* -268 "mesg" */
  { 1,  7, &builtin_symbols_pool0 [2182] }, /* -269 "message" */
  { 1, 15, &builtin_symbols_pool0 [2190] }, /* -270 "method_defined?" */
  { 1, 14, &builtin_symbols_pool0 [2206] }, /* -271 "method_missing" */
  { 1, 14, &builtin_symbols_pool0 [2221] }, /* -272 "method_removed" */
  { 1,  7, &builtin_symbols_pool0 [1907] }, /* -273 "methods" */
  { 1,  3, &builtin_symbols_pool0 [2236] }, /* -274 "min" */
  { 1, 11, &builtin_symbols_pool0 [2240] }, /* -275 "module_eval" */
  { 1, 15, &builtin_symbols_pool0 [2252] }, /* -276 "module_function" */
  { 1,  1, &builtin_symbols_pool0 [ 145] }, /* -277 "n" */
  { 1,  4, &builtin_symbols_pool0 [  65] }, /* -278 "name" */
  { 1,  5, &builtin_symbols_pool0 [2268] }, /* -279 "name=" */
  { 1,  5, &builtin_symbols_pool0 [2274] }, /* -280 "names" */
  { 1,  4, &builtin_symbols_pool0 [2280] }, /* -281 "nan?" */
  { 1,  7, &builtin_symbols_pool0 [2285] }, /* -282 "nesting" */
  { 1,  3, &builtin_symbols_pool0 [2293] }, /* -283 "new" */
  { 1,  4, &builtin_symbols_pool0 [2297] }, /* -284 "next" */
  { 1,  4, &builtin_symbols_pool0 [2302] }, /* -285 "nil?" */
  { 1,  3, &builtin_symbols_pool0 [ 161] }, /* -286 "num" */
  { 1,  3, &builtin_symbols_pool0 [2307] }, /* -287 "obj" */
  { 1,  9, &builtin_symbols_pool0 [2311] }, /* -288 "object_id" */
  { 1,  6, &builtin_symbols_pool0 [2321] }, /* -289 "offset" */
  { 1,  5, &builtin_symbols_pool0 [2328] }, /* -290 "other" */
  { 1,  1, &builtin_symbols_pool0 [ 505] }, /* -291 "p" */
  { 1,  9, &builtin_symbols_pool0 [2334] }, /* -292 "partition" */
  { 1,  7, &builtin_symbols_pool0 [2344] }, /* -293 "pattern" */
  { 1,  5, &builtin_symbols_pool0 [2352] }, /* -294 "pivot" */
  { 1,  4, &builtin_symbols_pool0 [2358] }, /* -295 "plen" */
  { 1,  3, &builtin_symbols_pool0 [2363] }, /* -296 "pop" */
  { 1,  3, &builtin_symbols_pool0 [2367] }, /* -297 "pos" */
  { 1,  6, &builtin_symbols_pool0 [2371] }, /* -298 "posnum" */
  { 1,  4, &builtin_symbols_pool0 [2378] }, /* -299 "post" */
  { 1,  3, &builtin_symbols_pool0 [2383] }, /* -300 "pre" */
  { 1,  7, &builtin_symbols_pool0 [2387] }, /* -301 "prepend" */
  { 1, 16, &builtin_symbols_pool0 [2395] }, /* -302 "prepend_features" */
  { 1,  9, &builtin_symbols_pool0 [2412] }, /* -303 "prepended" */
  { 1,  5, &builtin_symbols_pool0 [2422] }, /* -304 "print" */
  { 1,  6, &builtin_symbols_pool0 [2817] }, /* -305 "printf" */
  { 1,  7, &builtin_symbols_pool0 [2428] }, /* -306 "private" */
  { 1, 15, &builtin_symbols_pool0 [2436] }, /* -307 "private_methods" */
  { 1,  9, &builtin_symbols_pool0 [2452] }, /* -308 "protected" */
  { 1, 17, &builtin_symbols_pool0 [2462] }, /* -309 "protected_methods" */
  { 1,  6, &builtin_symbols_pool0 [2480] }, /* -310 "public" */
  { 1, 14, &builtin_symbols_pool0 [2487] }, /* -311 "public_methods" */
  { 1,  4, &builtin_symbols_pool0 [2502] }, /* -312 "push" */
  { 1,  4, &builtin_symbols_pool0 [2507] }, /* -313 "puts" */
  { 1,  3, &builtin_symbols_pool0 [2512] }, /* -314 "quo" */
  { 1,  1, &builtin_symbols_pool0 [  95] }, /* -315 "r" */
  { 1,  5, &builtin_symbols_pool0 [2516] }, /* -316 "raise" */
  { 1,  2, &builtin_symbols_pool0 [2384] }, /* -317 "re" */
  { 1,  6, &builtin_symbols_pool0 [2522] }, /* -318 "reduce" */
  { 1,  3, &builtin_symbols_pool0 [2529] }, /* -319 "reg" */
  { 1,  6, &builtin_symbols_pool0 [2533] }, /* -320 "rehash" */
  { 1,  6, &builtin_symbols_pool0 [2540] }, /* -321 "reject" */
  { 1,  7, &builtin_symbols_pool0 [2547] }, /* -322 "reject!" */
  { 1, 21, &builtin_symbols_pool0 [2555] }, /* -323 "remove_class_variable" */
  { 1, 12, &builtin_symbols_pool0 [2577] }, /* -324 "remove_const" */
  { 1, 24, &builtin_symbols_pool0 [2590] }, /* -325 "remove_instance_variable" */
  { 1, 13, &builtin_symbols_pool0 [2615] }, /* -326 "remove_method" */
  { 1,  7, &builtin_symbols_pool0 [ 780] }, /* -327 "replace" */
  { 1, 11, &builtin_symbols_pool0 [2629] }, /* -328 "respond_to?" */
  { 1, 19, &builtin_symbols_pool0 [2641] }, /* -329 "respond_to_missing?" */
  { 1,  6, &builtin_symbols_pool0 [  71] }, /* -330 "result" */
  { 1,  7, &builtin_symbols_pool0 [2661] }, /* -331 "result=" */
  { 1,  3, &builtin_symbols_pool0 [2669] }, /* -332 "ret" */
  { 1,  7, &builtin_symbols_pool0 [2673] }, /* -333 "reverse" */
  { 1,  8, &builtin_symbols_pool0 [2681] }, /* -334 "reverse!" */
  { 1,  3, &builtin_symbols_pool0 [2690] }, /* -335 "rhs" */
  { 1,  5, &builtin_symbols_pool0 [2694] }, /* -336 "right" */
  { 1,  6, &builtin_symbols_pool0 [2700] }, /* -337 "rindex" */
  { 1,  5, &builtin_symbols_pool0 [2707] }, /* -338 "round" */
  { 1,  2, &builtin_symbols_pool0 [ 882] }, /* -339 "rs" */
  { 1,  6, &builtin_symbols_pool0 [2713] }, /* -340 "rs_len" */
  { 1,  1, &builtin_symbols_pool0 [  62] }, /* -341 "s" */
  { 1,  4, &builtin_symbols_pool0 [2720] }, /* -342 "scan" */
  { 1,  6, &builtin_symbols_pool0 [2725] }, /* -343 "select" */
  { 1,  7, &builtin_symbols_pool0 [2732] }, /* -344 "select!" */
  { 1,  4, &builtin_symbols_pool0 [2740] }, /* -345 "send" */
  { 1, 13, &builtin_symbols_pool0 [2745] }, /* -346 "set_backtrace" */
  { 1,  5, &builtin_symbols_pool0 [3014] }, /* -347 "shift" */
  { 1, 15, &builtin_symbols_pool0 [2759] }, /* -348 "singleton_class" */
  { 1, 17, &builtin_symbols_pool0 [2775] }, /* -349 "singleton_methods" */
  { 1,  4, &builtin_symbols_pool0 [1023] }, /* -350 "size" */
  { 1,  5, &builtin_symbols_pool0 [2793] }, /* -351 "slice" */
  { 1,  4, &builtin_symbols_pool0 [2799] }, /* -352 "sort" */
  { 1,  5, &builtin_symbols_pool0 [2804] }, /* -353 "sort!" */
  { 1,  5, &builtin_symbols_pool0 [2810] }, /* -354 "split" */
  { 1,  7, &builtin_symbols_pool0 [2816] }, /* -355 "sprintf" */
  { 1,  5, &builtin_symbols_pool0 [2824] }, /* -356 "stack" */
  { 1,  5, &builtin_symbols_pool0 [2830] }, /* -357 "start" */
  { 1,  4, &builtin_symbols_pool0 [2836] }, /* -358 "step" */
  { 1, 10, &builtin_symbols_pool0 [2841] }, /* -359 "step_ratio" */
  { 1, 11, &builtin_symbols_pool0 [2852] }, /* -360 "step_ratio=" */
  { 1,  5, &builtin_symbols_pool0 [2864] }, /* -361 "store" */
  { 1,  3, &builtin_symbols_pool0 [2979] }, /* -362 "str" */
  { 1,  8, &builtin_symbols_pool0 [2870] }, /* -363 "str_each" */
  { 1,  3, &builtin_symbols_pool0 [1733] }, /* -364 "sub" */
  { 1,  4, &builtin_symbols_pool0 [1738] }, /* -365 "sub!" */
  { 1,  4, &builtin_symbols_pool0 [2879] }, /* -366 "succ" */
  { 1, 10, &builtin_symbols_pool0 [2884] }, /* -367 "superclass" */
  { 1,  2, &builtin_symbols_pool0 [2895] }, /* -368 "sv" */
  { 1,  3, &builtin_symbols_pool0 [2986] }, /* -369 "sym" */
  { 1,  1, &builtin_symbols_pool0 [  76] }, /* -370 "t" */
  { 1,  4, &builtin_symbols_pool0 [2898] }, /* -371 "tail" */
  { 1,  4, &builtin_symbols_pool0 [2903] }, /* -372 "this" */
  { 1,  5, &builtin_symbols_pool0 [2908] }, /* -373 "times" */
  { 1,  3, &builtin_symbols_pool0 [2914] }, /* -374 "tmp" */
  { 1,  4, &builtin_symbols_pool0 [2918] }, /* -375 "to_a" */
  { 1,  6, &builtin_symbols_pool0 [2923] }, /* -376 "to_ary" */
  { 1,  7, &builtin_symbols_pool0 [2930] }, /* -377 "to_enum" */
  { 1,  4, &builtin_symbols_pool0 [2938] }, /* -378 "to_f" */
  { 1,  7, &builtin_symbols_pool0 [2943] }, /* -379 "to_hash" */
  { 1,  4, &builtin_symbols_pool0 [2951] }, /* -380 "to_i" */
  { 1,  6, &builtin_symbols_pool0 [2956] }, /* -381 "to_int" */
  { 1,  7, &builtin_symbols_pool0 [2963] }, /* -382 "to_proc" */
  { 1,  4, &builtin_symbols_pool0 [2971] }, /* -383 "to_s" */
  { 1,  6, &builtin_symbols_pool0 [2976] }, /* -384 "to_str" */
  { 1,  6, &builtin_symbols_pool0 [2983] }, /* -385 "to_sym" */
  { 1,  8, &builtin_symbols_pool0 [2990] }, /* -386 "truncate" */
  { 1, 12, &builtin_symbols_pool0 [2999] }, /* -387 "undef_method" */
  { 1,  7, &builtin_symbols_pool0 [3012] }, /* -388 "unshift" */
  { 1,  6, &builtin_symbols_pool0 [3020] }, /* -389 "upcase" */
  { 1,  7, &builtin_symbols_pool0 [3027] }, /* -390 "upcase!" */
  { 1,  4, &builtin_symbols_pool0 [3035] }, /* -391 "upto" */
  { 1,  1, &builtin_symbols_pool0 [2896] }, /* -392 "v" */
  { 1,  3, &builtin_symbols_pool0 [1124] }, /* -393 "val" */
  { 1,  4, &builtin_symbols_pool0 [3040] }, /* -394 "vals" */
  { 1,  5, &builtin_symbols_pool0 [ 791] }, /* -395 "value" */
  { 1,  6, &builtin_symbols_pool0 [1756] }, /* -396 "value?" */
  { 1,  6, &builtin_symbols_pool0 [3045] }, /* -397 "values" */
  { 1,  1, &builtin_symbols_pool0 [ 673] }, /* -398 "x" */
  { 1,  1, &builtin_symbols_pool0 [ 101] }, /* -399 "y" */
  { 1,  1, &builtin_symbols_pool0 [3052] }, /* -400 "|" */
  { 1,  1, &builtin_symbols_pool0 [   4] }, /* -401 "~" */
};
