# https://github.com/j178/prek
name: Manual hooks

on: [pull_request]

permissions:
  contents: read

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: j178/prek-action@e98a699c41eb69ab013a45817a0406469a748f8d # v2.0.5
        with:
          install-only: true
      - name: Run manual pre-commit hooks
        run: prek run --color=always --all-files --hook-stage manual
