name: Ubuntu CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: sudo apt install ruby gperf bison
    - name: build and test
      run: ./minirake -j4 all test
      env:
        MRUBY_CONFIG: travis_config.rb
